USE [master]
GO
/****** Objeto: Database [GCS] Fecha de script: 18/05/2026 10:08:30 ******/
CREATE DATABASE [GCS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GCS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\GCS.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GCS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\GCS_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [GCS] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GCS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [GCS] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [GCS] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [GCS] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [GCS] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [GCS] SET ARITHABORT OFF 
GO
ALTER DATABASE [GCS] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [GCS] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [GCS] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [GCS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [GCS] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [GCS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [GCS] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [GCS] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [GCS] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [GCS] SET  DISABLE_BROKER 
GO
ALTER DATABASE [GCS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [GCS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [GCS] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [GCS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [GCS] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [GCS] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [GCS] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [GCS] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [GCS] SET  MULTI_USER 
GO
ALTER DATABASE [GCS] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [GCS] SET DB_CHAINING OFF 
GO
ALTER DATABASE [GCS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [GCS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [GCS] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [GCS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [GCS] SET QUERY_STORE = ON
GO
ALTER DATABASE [GCS] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [GCS]
GO
/****** Objeto: User [sistema] Fecha de script: 18/05/2026 10:08:30 ******/
CREATE USER [sistema] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [sistema]
GO
/****** Objeto: UserDefinedFunction [dbo].[_Cantidad_CIs_CMDB] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[_Cantidad_CIs_CMDB] 
(

)
RETURNS INT
AS
BEGIN
    declare @CANTIDAD AS INT

	declare @CANTIDAD_CIS AS INT

	SELECT  @CANTIDAD_CIS =      COUNT(dbo.ELEMENTOS_CONFIGURACION.ID_ELEMENTO_CONFIGURACION) 
FROM            dbo.ELEMENTOS_CONFIGURACION INNER JOIN
                         dbo.ESTADO_ELEMENTO_CONFIGURACION ON 
                         dbo.ELEMENTOS_CONFIGURACION.ID_ESTADO = dbo.ESTADO_ELEMENTO_CONFIGURACION.ID_ESTADO
GROUP BY dbo.ESTADO_ELEMENTO_CONFIGURACION.NOMBRE_ESTADO
HAVING        (dbo.ESTADO_ELEMENTO_CONFIGURACION.NOMBRE_ESTADO = 'ACTIVO')

     declare @CANTIDAD_LIC AS INT
SELECT     @CANTIDAD_LIC =   COUNT(ID_LICENCIA_ELE_CONF) 
FROM            dbo.LICENCIA_ELEMENTO_CONFIGURACION

     SET @CANTIDAD = @CANTIDAD_CIS + @CANTIDAD_LIC
	
    return @CANTIDAD
END


--PRINT  [dbo].[_Cantidad_CIs_CMDB]() 




GO
/****** Objeto: UserDefinedFunction [dbo].[_CANTIDAD_COMPONENTES_CI] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[_CANTIDAD_COMPONENTES_CI] 
(
@ID_CI	VARCHAR(MAX)=null
)
RETURNS varchar(max)
AS
BEGIN
    declare @msg AS VARCHAR(MAX)
	declare @CANTIDAD_COMPONENTES AS VARCHAR(MAX)
	SELECT   @CANTIDAD_COMPONENTES =     COUNT(ID_COMPONENTE) 
	FROM            dbo.COMPONENTES_ELEMENTO_CONFIGURACION
	GROUP BY ID_ELEMENTO_CONFIGURACION
	HAVING        (ID_ELEMENTO_CONFIGURACION = @ID_CI)
	IF(@CANTIDAD_COMPONENTES=0)
	   set @msg = 'Sin componentes registrados'
    else
	   set @msg = 'Tiene ' + @CANTIDAD_COMPONENTES + ' componentes registrados'
    return @msg
END


--PRINT [dbo].[_CANTIDAD_COMPONENTES_CI]( 16)




GO
/****** Objeto: UserDefinedFunction [dbo].[_formatear_fecha] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[_formatear_fecha] 
(
@FECHA datetime	
)
RETURNS varchar(max)
AS
BEGIN
	
	declare @_numero varchar(max) = ''
	set @_numero = CONVERT( VARCHAR(MAX),DAY(@FECHA)) + '/' + CONVERT( VARCHAR(MAX),MONTH(@FECHA)) + '/' + CONVERT( VARCHAR(MAX),YEAR(@FECHA))
	RETURN @_numero
END






GO
/****** Objeto: UserDefinedFunction [dbo].[_OBTENER_MODELO] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[_OBTENER_MODELO] 
(
    @ID_MODELO INT	
)
RETURNS VARCHAR(MAX)
AS
BEGIN
    DECLARE @_MODELO VARCHAR(MAX) = ''

    SELECT @_MODELO = NOMBRE
    FROM dbo.MODELO
    WHERE ID_MOD = @ID_MODELO

    RETURN @_MODELO
END






GO
/****** Objeto: UserDefinedFunction [dbo].[_obtner_codigo_derecho] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create FUNCTION [dbo].[_obtner_codigo_derecho] 
(
@DERECHO	VARCHAR(MAX)=null
)
RETURNS varchar(max)
AS
BEGIN
	declare @CODIGO_DERECHO int
	SET @CODIGO_DERECHO = -1
	IF(LEN(UPPER(ltrim(rtrim(@DERECHO))))<>0)
		BEGIN
			SELECT  @CODIGO_DERECHO = d.id_derecho FROM dbo.derecho as d
			where UPPER(ltrim(rtrim(d.nombre_derecho))) = UPPER(ltrim(rtrim(@DERECHO)))
		END	
	RETURN @CODIGO_DERECHO
END







GO
/****** Objeto: UserDefinedFunction [dbo].[_VERIFICA_VENCIMIENTO_LICENCIA] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[_VERIFICA_VENCIMIENTO_LICENCIA] 
(
@LICENCIA_PERPETUA	INT=null,
@FECHA_FIN_LICENCIA	DATETIME=null
)
RETURNS varchar(max)
AS
BEGIN
    declare @msg AS VARCHAR(MAX)
	IF(@LICENCIA_PERPETUA=1)
	   BEGIN
	        SET @msg='LICENCIA NO VENCE'
	   END
    ELSE IF(@LICENCIA_PERPETUA=0)
	   BEGIN
	        declare @DIAS AS INT
			SET @DIAS = DATEDIFF(DAY, GETDATE(), 
                         @FECHA_FIN_LICENCIA)
            IF (@DIAS<=0)
			    BEGIN
					 SET @msg='LICENCIA VENCIDA'
				END
            ELSE
			    BEGIN
				     SET @msg= 'DENTRO DE ' + CONVERT(VARCHAR(MAX), 
                         DATEDIFF(DAY, GETDATE(), @FECHA_FIN_LICENCIA)) + ' DIAS VENCE' 
				END 
	   END 	
    return @msg
END


--PRINT [dbo].[_CANTIDAD_COMPONENTES_CI]( 16)




GO
/****** Objeto: UserDefinedFunction [dbo].[obtener_estado_actual_seguimiento_elemento_congiguracion] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,ING. JOSE. S. ALVITES R.>
-- Create date: <Create Date, REQUE, LUNES; 09 DE JULIO DEL 2012>
-- Description:	<Description, OBTIENE LA CANTIDAD DE LITOS ACURRIDOS POR MES>
-- Comuniquese:	<Comuniquese al celular, 979-962-073>
-- =============================================
CREATE FUNCTION [dbo].[obtener_estado_actual_seguimiento_elemento_congiguracion] 
(
	@D_SEGUIMIENTO int
)
RETURNS varchar(max)
AS
begin
	declare @estados varchar(max) = ''
	declare @estado varchar(max) = ''
	DECLARE estados_cursor CURSOR FOR
SELECT        dbo.ESTADO_ACTUAL_ELEMENTO_CONFIGURACION.NOMBRE_ESTADO_ACTUL
FROM            dbo.DETALLE_ESTADO_ACTUAL_ELEMENTO_CONFIGURACION INNER JOIN
                         dbo.ESTADO_ACTUAL_ELEMENTO_CONFIGURACION ON 
                         dbo.DETALLE_ESTADO_ACTUAL_ELEMENTO_CONFIGURACION.ID_ESTADO_ACTUAL = dbo.ESTADO_ACTUAL_ELEMENTO_CONFIGURACION.ID_ESTADO_ACTUAL
WHERE        (dbo.DETALLE_ESTADO_ACTUAL_ELEMENTO_CONFIGURACION.ID_SEGUIMIENTO = @D_SEGUIMIENTO)
	OPEN estados_cursor
	FETCH NEXT FROM estados_cursor
	INTO @estado
	set @estados=''
	WHILE @@FETCH_STATUS = 0
	BEGIN
		 SET @estados=@estados + @estado + ', '
		 FETCH NEXT FROM estados_cursor INTO @estado
	END
	CLOSE estados_cursor
	DEALLOCATE estados_cursor
	if len(@estados)>0
		begin
			set @estados = SUBSTRING(@estados,1,len(@estados)-1)
		end
	else
		begin
			set @estados = '------'
		end
	return @estados
END

--print [dbo].[obtener_prerreqisito_asignatura] (2)




GO
/****** Objeto: UserDefinedFunction [dbo].[OBTENER_UBICACION_LICENCIA_AREA] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[OBTENER_UBICACION_LICENCIA_AREA] 
(
@_ID_LICENCIA_ELE_CONF	VARCHAR(MAX)=null,
@_TIPO_LICENCIA_ELE_CONF	VARCHAR(MAX)=null,
@_NOMBRE_LICENCIA_ELE_CONF	VARCHAR(MAX)=null
)
RETURNS varchar(max)
AS
BEGIN
    declare @_AREA VARCHAR(MAX)
	SELECT       @_AREA = A.Descripcion_Area
              
FROM          dbo.Local AS L INNER JOIN
              dbo.Sede as S ON l.Id_Sede = S.Id_Sede INNER JOIN
                         dbo.Area AS A ON l.Id_Local = A.Id_Local INNER JOIN
                         dbo.LICENCIA_ELEMENTO_CONFIGURACION AS LEC INNER JOIN
                         dbo.TIPO_LICENCIA_ELEMENTO_CONFIGURACION AS TLEC ON 
                         LEC.ID_TIPO_LICENCIA_CI = TLEC.ID_TIPO_LICENCIA_CI INNER JOIN
                         dbo.RELACION_LICENCIA_ELEMENTO_CONFIGURACION AS RLEC ON 
                         LEC.ID_LICENCIA_ELE_CONF = RLEC.ID_LICENCIA_ELE_CONF INNER
                          JOIN
                         dbo.ELEMENTOS_CONFIGURACION AS EC ON 
                         RLEC.ID_ELEMENTO_CONFIGURACION = EC.ID_ELEMENTO_CONFIGURACION
                          ON A.Id_Area = EC.LOCALIZACION_FISICA
GROUP BY LEC.ID_LICENCIA_ELE_CONF, TLEC.NOMBRE_LICENCIA_CI, 
                         LEC.NOMBRE, A.Descripcion_Area
HAVING        (LEC.ID_LICENCIA_ELE_CONF = @_ID_LICENCIA_ELE_CONF) AND 
                         (TLEC.NOMBRE_LICENCIA_CI = @_TIPO_LICENCIA_ELE_CONF) AND 
                         (LEC.NOMBRE = @_NOMBRE_LICENCIA_ELE_CONF)
    return @_AREA
END


--PRINT [dbo].[_CANTIDAD_COMPONENTES_CI]( 16)




GO
/****** Objeto: Table [dbo].[CLASIFICACION_DATOS_ELEMENTO_CONFIGURACION] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CLASIFICACION_DATOS_ELEMENTO_CONFIGURACION](
	[ID_CLASIFICACION] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE_CLASIFICACION] [varchar](50) NOT NULL,
 CONSTRAINT [PK_CLASIFICACION_DATOS_ELEMENTO_CONFIGURACION] PRIMARY KEY CLUSTERED 
(
	[ID_CLASIFICACION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[SEGUIMIENTO_ELEMENTO_CONFIGURACION] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SEGUIMIENTO_ELEMENTO_CONFIGURACION](
	[ID_SEGUIMIENTO] [int] IDENTITY(1,1) NOT NULL,
	[ID_ELEMENTO_CONFIGURACION] [int] NOT NULL,
	[RESPONSABLE_SEGUIMIENTO] [int] NOT NULL,
	[FECHA_SEGUIMIENTO] [datetime] NOT NULL,
	[ID_CLASIFICACION] [int] NOT NULL,
	[RELACION_OTROS_CIS] [bit] NOT NULL,
	[CUMPLE_POLITICAS_GESTION_CONFIGURACION_ORGANIZACION] [bit] NOT NULL,
	[OBSERVACION_SEGUIMIENTO] [varchar](max) NOT NULL,
 CONSTRAINT [PK_SEGUIMIENTO_ELEMENTO_CONFIGURACION] PRIMARY KEY CLUSTERED 
(
	[ID_SEGUIMIENTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[Usuario] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuario](
	[Id_Uusario] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](25) NOT NULL,
	[ApePat] [varchar](25) NOT NULL,
	[ApeMat] [varchar](25) NOT NULL,
	[Telefono] [varchar](9) NOT NULL,
	[Email] [varchar](max) NOT NULL,
	[Login] [varchar](50) NOT NULL,
	[Password] [varchar](50) NOT NULL,
	[Estado] [bit] NOT NULL,
	[ID_CARGO] [int] NULL,
	[Id_Area] [int] NULL,
 CONSTRAINT [pk_Usuario_Id_Usuario] PRIMARY KEY CLUSTERED 
(
	[Id_Uusario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Objeto: View [dbo].[VISTA_DETALLE_SEGUIMIENTO_ELEMENTOS_CONFIGURACION] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VISTA_DETALLE_SEGUIMIENTO_ELEMENTOS_CONFIGURACION]
AS
SELECT        dbo.SEGUIMIENTO_ELEMENTO_CONFIGURACION.ID_SEGUIMIENTO AS [ID SEGUIMIENTO], 
                         dbo.SEGUIMIENTO_ELEMENTO_CONFIGURACION.ID_ELEMENTO_CONFIGURACION AS [ID CI], 
                         dbo.SEGUIMIENTO_ELEMENTO_CONFIGURACION.RESPONSABLE_SEGUIMIENTO AS [ID RESPONSABLE], 
                         dbo.Usuario.Nombre + ' ' + dbo.Usuario.ApePat + ' ' + dbo.Usuario.ApeMat AS RESPONSABLE, 
                         dbo.SEGUIMIENTO_ELEMENTO_CONFIGURACION.FECHA_SEGUIMIENTO AS [FECHA SEGUIMIENTO], 
                         dbo.CLASIFICACION_DATOS_ELEMENTO_CONFIGURACION.NOMBRE_CLASIFICACION AS [CLASIFICACION DATOS], 
                         dbo.obtener_estado_actual_seguimiento_elemento_congiguracion(dbo.SEGUIMIENTO_ELEMENTO_CONFIGURACION.ID_SEGUIMIENTO) 
                         AS [ESTADO ACTUAL], CASE dbo.SEGUIMIENTO_ELEMENTO_CONFIGURACION.RELACION_OTROS_CIS WHEN 1 THEN 'SI' ELSE 'NO' END AS [RELACION CIS],
                          CASE dbo.SEGUIMIENTO_ELEMENTO_CONFIGURACION.CUMPLE_POLITICAS_GESTION_CONFIGURACION_ORGANIZACION WHEN 1 THEN 'SI' ELSE 'NO' END
                          AS [CUMPLE POLITICA GESTION CONIGURACION ORGANIZACION], 
                         dbo.SEGUIMIENTO_ELEMENTO_CONFIGURACION.OBSERVACION_SEGUIMIENTO AS OBSERVACION
FROM            dbo.SEGUIMIENTO_ELEMENTO_CONFIGURACION INNER JOIN
                         dbo.CLASIFICACION_DATOS_ELEMENTO_CONFIGURACION ON 
                         dbo.SEGUIMIENTO_ELEMENTO_CONFIGURACION.ID_CLASIFICACION = dbo.CLASIFICACION_DATOS_ELEMENTO_CONFIGURACION.ID_CLASIFICACION INNER
                          JOIN
                         dbo.Usuario ON dbo.SEGUIMIENTO_ELEMENTO_CONFIGURACION.RESPONSABLE_SEGUIMIENTO = dbo.Usuario.Id_Uusario





GO
/****** Objeto: Table [dbo].[Area] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Area](
	[Id_Area] [int] IDENTITY(1,1) NOT NULL,
	[Codigo_Area] [varchar](6) NOT NULL,
	[Descripcion_Area] [varchar](max) NOT NULL,
	[Nro_Piso] [char](1) NOT NULL,
	[Nro_Ambiente] [varchar](3) NOT NULL,
	[Id_Local] [int] NOT NULL,
 CONSTRAINT [PK_Area_1] PRIMARY KEY CLUSTERED 
(
	[Id_Area] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[DESCRIPCION_ELEMENTO CONFIGURACION] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DESCRIPCION_ELEMENTO CONFIGURACION](
	[ID_DESCRIPCION] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE_DESCRIPCION] [varchar](max) NOT NULL,
	[ID_TIPO] [int] NULL,
 CONSTRAINT [PK_DESCRIPCION_ELEMENTO CONFIGURACION] PRIMARY KEY CLUSTERED 
(
	[ID_DESCRIPCION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[ELEMENTOS_CONFIGURACION] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ELEMENTOS_CONFIGURACION](
	[ID_ELEMENTO_CONFIGURACION] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE_ELEMENTO_CONFIGURACION] [varchar](max) NULL,
	[ID_TIPO] [int] NULL,
	[ID_ESTADO] [int] NULL,
	[PROPIETARIO] [int] NULL,
	[ID_DESCRIPCION] [int] NULL,
	[ID_IMP_ELE_CONF_HAR] [int] NULL,
	[LOCALIZACION_FISICA] [int] NULL,
	[FECHA_REGISTRO] [datetime] NULL,
	[RESPONSABLE_REGISTRO] [int] NULL,
	[ID_NIVEL] [int] NULL,
	[NRO_SERIE] [varchar](max) NULL,
	[FABRICANTE_O_PROVEEDOR] [varchar](max) NULL,
	[ID_MAR] [int] NULL,
	[ID_MOD] [int] NULL,
	[IP] [varchar](15) NULL,
	[GATEWAY] [varchar](15) NULL,
	[GRUPO_TRABAJO] [varchar](max) NULL,
 CONSTRAINT [PK_ELE_CONF_HAR_1] PRIMARY KEY CLUSTERED 
(
	[ID_ELEMENTO_CONFIGURACION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[ESTADO_ELEMENTO_CONFIGURACION] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ESTADO_ELEMENTO_CONFIGURACION](
	[ID_ESTADO] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE_ESTADO] [varchar](15) NOT NULL,
 CONSTRAINT [PK_ESTADO_ELEMENTO_CONFIGURACION] PRIMARY KEY CLUSTERED 
(
	[ID_ESTADO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[Local] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Local](
	[Id_Local] [int] IDENTITY(1,1) NOT NULL,
	[Codigo_Local] [varchar](6) NOT NULL,
	[Nombre_Local] [varchar](50) NULL,
	[Direccion_Local] [varchar](50) NOT NULL,
	[Id_Sede] [int] NOT NULL,
	[Cod_Ubi] [varchar](9) NOT NULL,
	[Telefono_local] [varchar](9) NULL,
	[Pagnia_Web_Local] [varchar](max) NULL,
	[Email_Local] [varchar](max) NULL,
	[Total_CIS_Local] [int] NULL,
 CONSTRAINT [PK_Local_1] PRIMARY KEY CLUSTERED 
(
	[Id_Local] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[MARCA] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MARCA](
	[ID_MAR] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](max) NOT NULL,
 CONSTRAINT [PK_Marca] PRIMARY KEY CLUSTERED 
(
	[ID_MAR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[MODELO] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MODELO](
	[ID_MOD] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](max) NOT NULL,
 CONSTRAINT [PK_Modelo] PRIMARY KEY CLUSTERED 
(
	[ID_MOD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[Personal] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Personal](
	[Id_Personal] [int] IDENTITY(1,1) NOT NULL,
	[Codigo_Personal] [varchar](5) NOT NULL,
	[Nombre_Personal] [varchar](25) NOT NULL,
	[ApePat_Personal] [varchar](25) NOT NULL,
	[ApeMat_Personal] [varchar](25) NOT NULL,
	[Id_Tipo_Documento] [int] NOT NULL,
	[Nro_Dni_Personal] [varchar](max) NOT NULL,
	[Id_prof_ocup] [int] NOT NULL,
	[Tel_Personal] [varchar](9) NULL,
	[Email_Personal] [varchar](max) NULL,
	[Id_Area] [int] NOT NULL,
	[Id_Dependencia] [int] NOT NULL,
	[Estado_Personal] [bit] NOT NULL,
	[ID_CARGO] [int] NULL,
 CONSTRAINT [PK_Personal] PRIMARY KEY CLUSTERED 
(
	[Id_Personal] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[Sede] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Sede](
	[Id_Sede] [int] IDENTITY(1,1) NOT NULL,
	[CodIgo_Sede] [varchar](2) NOT NULL,
	[Descripcion_Sede] [varchar](30) NOT NULL,
 CONSTRAINT [PK_Sede] PRIMARY KEY CLUSTERED 
(
	[Id_Sede] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[TIPOS_ELEMENTO_CONFIGURACION] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPOS_ELEMENTO_CONFIGURACION](
	[ID_TIPO] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE_TIPO] [varchar](max) NOT NULL,
 CONSTRAINT [PK_ELE_CONF_HAR] PRIMARY KEY CLUSTERED 
(
	[ID_TIPO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[Ubigeo] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ubigeo](
	[Cod_Ubi] [varchar](9) NOT NULL,
	[Codigo] [varchar](70) NULL,
	[Distrito] [varchar](max) NOT NULL,
	[Provincia] [varchar](max) NOT NULL,
	[Departamento] [varchar](max) NOT NULL,
 CONSTRAINT [PK_Ubigeo] PRIMARY KEY CLUSTERED 
(
	[Cod_Ubi] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Objeto: View [dbo].[VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION]
AS
SELECT        dbo.ELEMENTOS_CONFIGURACION.ID_ELEMENTO_CONFIGURACION AS [ID CI], dbo.ELEMENTOS_CONFIGURACION.NOMBRE_ELEMENTO_CONFIGURACION AS [NOMBRE CI], 
                         dbo.TIPOS_ELEMENTO_CONFIGURACION.NOMBRE_TIPO AS [TIPO CI], dbo.ELEMENTOS_CONFIGURACION.NRO_SERIE AS [NRO. SERIE], 
                         dbo.ELEMENTOS_CONFIGURACION.FABRICANTE_O_PROVEEDOR AS [FABRICANTE / PROVEEDOR], dbo.MARCA.NOMBRE AS MARCA, dbo.MODELO.NOMBRE AS MODELO, 
                         dbo.ESTADO_ELEMENTO_CONFIGURACION.NOMBRE_ESTADO AS ESTADO, dbo.[DESCRIPCION_ELEMENTO CONFIGURACION].NOMBRE_DESCRIPCION AS [DESCRIPCION CI], dbo.Sede.Descripcion_Sede AS SEDE, 
                         dbo.Local.Nombre_Local AS LOCAL, dbo.Ubigeo.Departamento + ' / ' + dbo.Ubigeo.Provincia + ' / ' + dbo.Ubigeo.Distrito AS UBICACION, dbo.Local.Direccion_Local AS DIRECCION, dbo.Area.Descripcion_Area AS AREA, 
                         dbo.Area.Nro_Piso AS [NRO PISO], dbo.Area.Nro_Ambiente AS [NRO AMBIENTE], dbo.ELEMENTOS_CONFIGURACION.IP, dbo.ELEMENTOS_CONFIGURACION.GATEWAY, 
                         dbo.ELEMENTOS_CONFIGURACION.GRUPO_TRABAJO AS [GRUPO TRABAJO], dbo.Personal.Nombre_Personal + ' ' + dbo.Personal.ApePat_Personal + ' ' + dbo.Personal.ApeMat_Personal AS PROPIETARIO
FROM            dbo.Local INNER JOIN
                         dbo.Sede ON dbo.Local.Id_Sede = dbo.Sede.Id_Sede INNER JOIN
                         dbo.Area ON dbo.Local.Id_Local = dbo.Area.Id_Local INNER JOIN
                         dbo.ELEMENTOS_CONFIGURACION INNER JOIN
                         dbo.TIPOS_ELEMENTO_CONFIGURACION ON dbo.ELEMENTOS_CONFIGURACION.ID_TIPO = dbo.TIPOS_ELEMENTO_CONFIGURACION.ID_TIPO INNER JOIN
                         dbo.MARCA ON dbo.ELEMENTOS_CONFIGURACION.ID_MAR = dbo.MARCA.ID_MAR INNER JOIN
                         dbo.MODELO ON dbo.ELEMENTOS_CONFIGURACION.ID_MOD = dbo.MODELO.ID_MOD INNER JOIN
                         dbo.ESTADO_ELEMENTO_CONFIGURACION ON dbo.ELEMENTOS_CONFIGURACION.ID_ESTADO = dbo.ESTADO_ELEMENTO_CONFIGURACION.ID_ESTADO INNER JOIN
                         dbo.[DESCRIPCION_ELEMENTO CONFIGURACION] ON dbo.ELEMENTOS_CONFIGURACION.ID_DESCRIPCION = dbo.[DESCRIPCION_ELEMENTO CONFIGURACION].ID_DESCRIPCION ON 
                         dbo.Area.Id_Area = dbo.ELEMENTOS_CONFIGURACION.LOCALIZACION_FISICA INNER JOIN
                         dbo.Ubigeo ON dbo.Local.Cod_Ubi = dbo.Ubigeo.Cod_Ubi INNER JOIN
                         dbo.Personal ON dbo.ELEMENTOS_CONFIGURACION.PROPIETARIO = dbo.Personal.Id_Personal
GROUP BY dbo.ELEMENTOS_CONFIGURACION.ID_ELEMENTO_CONFIGURACION, dbo.ELEMENTOS_CONFIGURACION.NOMBRE_ELEMENTO_CONFIGURACION, dbo.TIPOS_ELEMENTO_CONFIGURACION.NOMBRE_TIPO, 
                         dbo.ELEMENTOS_CONFIGURACION.NRO_SERIE, dbo.ELEMENTOS_CONFIGURACION.FABRICANTE_O_PROVEEDOR, dbo.MARCA.NOMBRE, dbo.MODELO.NOMBRE, 
                         dbo.ESTADO_ELEMENTO_CONFIGURACION.NOMBRE_ESTADO, dbo.[DESCRIPCION_ELEMENTO CONFIGURACION].NOMBRE_DESCRIPCION, dbo.Local.Nombre_Local, 
                         dbo.Ubigeo.Departamento + ' / ' + dbo.Ubigeo.Provincia + ' / ' + dbo.Ubigeo.Distrito, dbo.Local.Direccion_Local, dbo.Area.Descripcion_Area, dbo.Area.Nro_Piso, dbo.Area.Nro_Ambiente, dbo.Sede.Descripcion_Sede, 
                         dbo.ELEMENTOS_CONFIGURACION.IP, dbo.ELEMENTOS_CONFIGURACION.GATEWAY, dbo.ELEMENTOS_CONFIGURACION.GRUPO_TRABAJO, dbo.Personal.Nombre_Personal, dbo.Personal.ApePat_Personal, 
                         dbo.Personal.ApeMat_Personal




GO
/****** Objeto: View [dbo].[VISTA_SEGUIMIENTO_DETALLE_ELEMENTO_CONFIGURACION] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VISTA_SEGUIMIENTO_DETALLE_ELEMENTO_CONFIGURACION]
AS
SELECT        TOP (100) PERCENT dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[ID CI], 
                         dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[NOMBRE CI], dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[TIPO CI], 
                         dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[NRO. SERIE], 
                         dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[FABRICANTE / PROVEEDOR], dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.MARCA, 
                         dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.MODELO, dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.ESTADO, 
                         dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[DESCRIPCION CI], dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.SEDE, 
                         dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.LOCAL, dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.UBICACION, 
                         dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.DIRECCION, dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.AREA, 
                         dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[NRO PISO], dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[NRO AMBIENTE], 
                         dbo.VISTA_DETALLE_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[ID SEGUIMIENTO], 
                         dbo.VISTA_DETALLE_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[ID RESPONSABLE], 
                         dbo.VISTA_DETALLE_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.RESPONSABLE, 
                         dbo.VISTA_DETALLE_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[FECHA SEGUIMIENTO], 
                         dbo.VISTA_DETALLE_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[CLASIFICACION DATOS], 
                         dbo.VISTA_DETALLE_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[ESTADO ACTUAL], 
                         dbo.VISTA_DETALLE_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[RELACION CIS], 
                         dbo.VISTA_DETALLE_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[CUMPLE POLITICA GESTION CONIGURACION ORGANIZACION], 
                         dbo.VISTA_DETALLE_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.OBSERVACION, dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.IP, 
                         dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.GATEWAY, dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[GRUPO TRABAJO], 
                         dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.PROPIETARIO
FROM            dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION INNER JOIN
                         dbo.VISTA_DETALLE_SEGUIMIENTO_ELEMENTOS_CONFIGURACION ON 
                         dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[ID CI] = dbo.VISTA_DETALLE_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[ID CI]





GO
/****** Objeto: View [dbo].[Vista_DatosCorrectosCI] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[Vista_DatosCorrectosCI]
AS
SELECT        TOP (100) PERCENT dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.AREA, dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[TIPO CI], 
                         dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[DESCRIPCION CI], dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[NOMBRE CI], 
                         CONVERT(DATETIME, CONVERT(VARCHAR(11), dbo.VISTA_DETALLE_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[FECHA SEGUIMIENTO])) 
                         AS [FECHA SEGUIMIENTO]
FROM            dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION INNER JOIN
                         dbo.VISTA_DETALLE_SEGUIMIENTO_ELEMENTOS_CONFIGURACION ON 
                         dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[ID CI] = dbo.VISTA_DETALLE_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[ID CI]
WHERE        (dbo.VISTA_DETALLE_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[CLASIFICACION DATOS] = 'DATOS REGISTRADOS CORRECTAMENTE') AND 
                         (dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.ESTADO = 'ACTIVO')





GO
/****** Objeto: View [dbo].[Vista_DatosIncorrectosCI] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[Vista_DatosIncorrectosCI]
AS
SELECT        TOP (100) PERCENT dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.AREA, dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[TIPO CI], 
                         dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[DESCRIPCION CI], dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[NOMBRE CI], 
                         CONVERT(DATETIME, CONVERT(VARCHAR(11), dbo.VISTA_DETALLE_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[FECHA SEGUIMIENTO])) 
                         AS [FECHA SEGUIMIENTO]
FROM            dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION INNER JOIN
                         dbo.VISTA_DETALLE_SEGUIMIENTO_ELEMENTOS_CONFIGURACION ON 
                         dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[ID CI] = dbo.VISTA_DETALLE_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[ID CI]
WHERE        (dbo.VISTA_DETALLE_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[CLASIFICACION DATOS] = 'DATOS REGISTRADOS INCORRECTAMENTE') AND 
                         (dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.ESTADO = 'ACTIVO')





GO
/****** Objeto: View [dbo].[Vista_CIs_Seguidos] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[Vista_CIs_Seguidos]
AS
SELECT        TOP (100) PERCENT dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.AREA, 
                         dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[NRO PISO], dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[NRO AMBIENTE], 
                         dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[TIPO CI], dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[DESCRIPCION CI], 
                         dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[NOMBRE CI], 
                         dbo.VISTA_DETALLE_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[ESTADO ACTUAL], 
                         dbo.VISTA_DETALLE_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.OBSERVACION, CONVERT(DATETIME, CONVERT(VARCHAR(11), 
                         dbo.VISTA_DETALLE_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[FECHA SEGUIMIENTO])) AS [FECHA SEGUIMIENTO]
FROM            dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION INNER JOIN
                         dbo.VISTA_DETALLE_SEGUIMIENTO_ELEMENTOS_CONFIGURACION ON 
                         dbo.VISTA_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[ID CI] = dbo.VISTA_DETALLE_SEGUIMIENTO_ELEMENTOS_CONFIGURACION.[ID CI]





GO
/****** Objeto: Table [dbo].[RELACION_LICENCIA_ELEMENTO_CONFIGURACION] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RELACION_LICENCIA_ELEMENTO_CONFIGURACION](
	[ID_RELACION] [int] IDENTITY(1,1) NOT NULL,
	[ID_ELEMENTO_CONFIGURACION] [int] NOT NULL,
	[ID_LICENCIA_ELE_CONF] [int] NOT NULL,
 CONSTRAINT [PK_RELACION_LICENCIA_ELEMENTO_CONFIGURACION] PRIMARY KEY CLUSTERED 
(
	[ID_RELACION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: View [dbo].[V¡ISTA_RELACION_LICENCIAS_ELEMENTOS_CONFIGURACION] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[V¡ISTA_RELACION_LICENCIAS_ELEMENTOS_CONFIGURACION]
AS
SELECT        dbo.RELACION_LICENCIA_ELEMENTO_CONFIGURACION.ID_RELACION AS [ID RE], 
                         dbo.RELACION_LICENCIA_ELEMENTO_CONFIGURACION.ID_ELEMENTO_CONFIGURACION AS [ID CI], 
                         dbo.TIPOS_ELEMENTO_CONFIGURACION.NOMBRE_TIPO AS [TIPO CI], 
                         dbo.ELEMENTOS_CONFIGURACION.NOMBRE_ELEMENTO_CONFIGURACION AS [NOMBRE CI], 
                         dbo.ELEMENTOS_CONFIGURACION.NRO_SERIE AS [NRO SERIE], 
                         dbo.Personal.Nombre_Personal + ' ' + dbo.Personal.ApePat_Personal + ' ' + dbo.Personal.ApeMat_Personal AS PROPIETARIO, 
                         dbo.[DESCRIPCION_ELEMENTO CONFIGURACION].NOMBRE_DESCRIPCION AS [DESCRIPCION CI], 
                         dbo.RELACION_LICENCIA_ELEMENTO_CONFIGURACION.ID_LICENCIA_ELE_CONF, dbo.Sede.Descripcion_Sede AS SEDE, 
                         dbo.Local.Nombre_Local AS LOCAL, dbo.Area.Descripcion_Area AS AREA, dbo.Area.Nro_Piso AS [NRO PISO], 
                         dbo.Area.Nro_Ambiente AS [NRO AMBIENTE]
FROM            dbo.Local INNER JOIN
                         dbo.Sede ON dbo.Local.Id_Sede = dbo.Sede.Id_Sede INNER JOIN
                         dbo.Area ON dbo.Local.Id_Local = dbo.Area.Id_Local INNER JOIN
                         dbo.RELACION_LICENCIA_ELEMENTO_CONFIGURACION INNER JOIN
                         dbo.ELEMENTOS_CONFIGURACION ON 
                         dbo.RELACION_LICENCIA_ELEMENTO_CONFIGURACION.ID_ELEMENTO_CONFIGURACION = dbo.ELEMENTOS_CONFIGURACION.ID_ELEMENTO_CONFIGURACION
                          INNER JOIN
                         dbo.TIPOS_ELEMENTO_CONFIGURACION ON dbo.ELEMENTOS_CONFIGURACION.ID_TIPO = dbo.TIPOS_ELEMENTO_CONFIGURACION.ID_TIPO INNER JOIN
                         dbo.Personal ON dbo.ELEMENTOS_CONFIGURACION.PROPIETARIO = dbo.Personal.Id_Personal INNER JOIN
                         dbo.[DESCRIPCION_ELEMENTO CONFIGURACION] ON 
                         dbo.ELEMENTOS_CONFIGURACION.ID_DESCRIPCION = dbo.[DESCRIPCION_ELEMENTO CONFIGURACION].ID_DESCRIPCION ON 
                         dbo.Area.Id_Area = dbo.ELEMENTOS_CONFIGURACION.LOCALIZACION_FISICA AND dbo.Area.Id_Area = dbo.Personal.Id_Area





GO
/****** Objeto: Table [dbo].[LICENCIA_ELEMENTO_CONFIGURACION] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LICENCIA_ELEMENTO_CONFIGURACION](
	[ID_LICENCIA_ELE_CONF] [int] IDENTITY(1,1) NOT NULL,
	[ID_TIPO_LICENCIA_CI] [int] NOT NULL,
	[NOMBRE] [varchar](max) NOT NULL,
	[VERSION] [varchar](max) NOT NULL,
	[ID_SUSCRIPCION_LICENCIA_CI] [int] NOT NULL,
	[FECHA_INICIO] [datetime] NULL,
	[FECHA_FIN] [datetime] NULL,
	[LICENCIA_PERPETUA] [bit] NOT NULL,
	[DESCRIPCION] [varchar](max) NOT NULL,
 CONSTRAINT [PK_LICENCIA_ELEMENTO_CONFIGURACION] PRIMARY KEY CLUSTERED 
(
	[ID_LICENCIA_ELE_CONF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[SUSCRIPCION_LICENCIA-ELEMENTO_CONFIGURACION] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SUSCRIPCION_LICENCIA-ELEMENTO_CONFIGURACION](
	[ID_SUSCRIPCION_LICENCIA_CI] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE_SUSCRIPCION_LICENCIA_CI] [varchar](25) NOT NULL,
	[ID_TIPO_LICENCIA_CI] [int] NOT NULL,
 CONSTRAINT [PK_SUSCRIPCION_LICENCIA-ELEMENTO_CONFIGURACION] PRIMARY KEY CLUSTERED 
(
	[ID_SUSCRIPCION_LICENCIA_CI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[TIPO_LICENCIA_ELEMENTO_CONFIGURACION] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPO_LICENCIA_ELEMENTO_CONFIGURACION](
	[ID_TIPO_LICENCIA_CI] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE_LICENCIA_CI] [varchar](max) NOT NULL,
 CONSTRAINT [PK_TIPO_LICENCIA_ELEMENTO_CONFIGURACION] PRIMARY KEY CLUSTERED 
(
	[ID_TIPO_LICENCIA_CI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Objeto: View [dbo].[V¡ISTA_RELACION_LICENCIAS_ELEMENTOS_CONFIGURACION_2] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[V¡ISTA_RELACION_LICENCIAS_ELEMENTOS_CONFIGURACION_2]
AS
SELECT        dbo.TIPO_LICENCIA_ELEMENTO_CONFIGURACION.NOMBRE_LICENCIA_CI, 
                         dbo.[SUSCRIPCION_LICENCIA-ELEMENTO_CONFIGURACION].NOMBRE_SUSCRIPCION_LICENCIA_CI, 
                         dbo.TIPOS_ELEMENTO_CONFIGURACION.NOMBRE_TIPO, dbo.ELEMENTOS_CONFIGURACION.NOMBRE_ELEMENTO_CONFIGURACION, 
                         dbo.ELEMENTOS_CONFIGURACION.ID_ELEMENTO_CONFIGURACION
FROM            dbo.LICENCIA_ELEMENTO_CONFIGURACION INNER JOIN
                         dbo.TIPO_LICENCIA_ELEMENTO_CONFIGURACION ON 
                         dbo.LICENCIA_ELEMENTO_CONFIGURACION.ID_TIPO_LICENCIA_CI = dbo.TIPO_LICENCIA_ELEMENTO_CONFIGURACION.ID_TIPO_LICENCIA_CI INNER JOIN
                         dbo.[SUSCRIPCION_LICENCIA-ELEMENTO_CONFIGURACION] ON 
                         dbo.LICENCIA_ELEMENTO_CONFIGURACION.ID_SUSCRIPCION_LICENCIA_CI = dbo.[SUSCRIPCION_LICENCIA-ELEMENTO_CONFIGURACION].ID_SUSCRIPCION_LICENCIA_CI
                          AND 
                         dbo.TIPO_LICENCIA_ELEMENTO_CONFIGURACION.ID_TIPO_LICENCIA_CI = dbo.[SUSCRIPCION_LICENCIA-ELEMENTO_CONFIGURACION].ID_TIPO_LICENCIA_CI
                          INNER JOIN
                         dbo.RELACION_LICENCIA_ELEMENTO_CONFIGURACION ON 
                         dbo.LICENCIA_ELEMENTO_CONFIGURACION.ID_LICENCIA_ELE_CONF = dbo.RELACION_LICENCIA_ELEMENTO_CONFIGURACION.ID_LICENCIA_ELE_CONF INNER
                          JOIN
                         dbo.ELEMENTOS_CONFIGURACION ON 
                         dbo.RELACION_LICENCIA_ELEMENTO_CONFIGURACION.ID_ELEMENTO_CONFIGURACION = dbo.ELEMENTOS_CONFIGURACION.ID_ELEMENTO_CONFIGURACION
                          INNER JOIN
                         dbo.TIPOS_ELEMENTO_CONFIGURACION ON dbo.ELEMENTOS_CONFIGURACION.ID_TIPO = dbo.TIPOS_ELEMENTO_CONFIGURACION.ID_TIPO





GO
/****** Objeto: View [dbo].[View_2] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[View_2]
AS
SELECT        ID_ELEMENTO_CONFIGURACION, CONVERT(DATETIME, CONVERT(VARCHAR(11), FECHA_SEGUIMIENTO)) AS Expr1
FROM            dbo.SEGUIMIENTO_ELEMENTO_CONFIGURACION
WHERE        (ID_ELEMENTO_CONFIGURACION = 16) AND (CONVERT(DATETIME, CONVERT(VARCHAR(11), FECHA_SEGUIMIENTO)) >= CONVERT(DATETIME, 
                         CONVERT(VARCHAR(11), GETDATE())))





GO
/****** Objeto: View [dbo].[VISTA_AREAS] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VISTA_AREAS]
AS
SELECT        dbo.Area.Id_Area AS [ID AREA], dbo.Sede.Descripcion_Sede AS SEDE, dbo.Local.Nombre_Local AS LOCAL, 
                         dbo.Local.Direccion_Local + ' - -' + dbo.Ubigeo.Departamento + ' / ' + dbo.Ubigeo.Provincia + ' / ' + dbo.Ubigeo.Distrito AS [DIRECCION LOCAL], 
                         dbo.Area.Codigo_Area AS [CODIGO AREA], dbo.Area.Descripcion_Area AS AREA, dbo.Area.Nro_Piso AS [NRO PISO], 
                         dbo.Area.Nro_Ambiente AS [NRO AMBIENTE], dbo.Local.Id_Local AS [ID LOCAL]
FROM            dbo.Sede INNER JOIN
                         dbo.Local ON dbo.Sede.Id_Sede = dbo.Local.Id_Sede INNER JOIN
                         dbo.Area ON dbo.Local.Id_Local = dbo.Area.Id_Local INNER JOIN
                         dbo.Ubigeo ON dbo.Local.Cod_Ubi = dbo.Ubigeo.Cod_Ubi





GO
/****** Objeto: Table [dbo].[IMPACTO_COMERCIAL_ELE_CONF_HAR] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IMPACTO_COMERCIAL_ELE_CONF_HAR](
	[ID_IMP_ELE_CONF_HAR] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](max) NOT NULL,
 CONSTRAINT [PK_IMPACTO_COMERCIAL_ELE_CONF_HAR] PRIMARY KEY CLUSTERED 
(
	[ID_IMP_ELE_CONF_HAR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[NIVEL_PRIORIDAD] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NIVEL_PRIORIDAD](
	[ID_NIVEL] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE_NIVEL] [varchar](8) NOT NULL,
 CONSTRAINT [PK_NIVEL_PRIORIDAD] PRIMARY KEY CLUSTERED 
(
	[ID_NIVEL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: View [dbo].[VISTA_CIs_ASIGNAR_COMPONENTES] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VISTA_CIs_ASIGNAR_COMPONENTES]
AS
SELECT        dbo.ELEMENTOS_CONFIGURACION.ID_ELEMENTO_CONFIGURACION AS [ID CI], dbo.ELEMENTOS_CONFIGURACION.NOMBRE_ELEMENTO_CONFIGURACION AS [NOMBRE CI], 
                         dbo.TIPOS_ELEMENTO_CONFIGURACION.ID_TIPO AS [ID TIPO CI], dbo.TIPOS_ELEMENTO_CONFIGURACION.NOMBRE_TIPO AS [NOMBRE TIPO CI], 
                         dbo.ESTADO_ELEMENTO_CONFIGURACION.NOMBRE_ESTADO AS [ESTADO CI], dbo.Personal.Id_Personal AS [ID PROPIETARIO], 
                         dbo.Personal.Nombre_Personal + ' ' + dbo.Personal.ApePat_Personal + ' ' + dbo.Personal.ApeMat_Personal AS PROPIETARIO, dbo.[DESCRIPCION_ELEMENTO CONFIGURACION].NOMBRE_DESCRIPCION AS [DESCRIPCION CI], 
                         dbo.IMPACTO_COMERCIAL_ELE_CONF_HAR.NOMBRE AS [IMPACTO CI], dbo.Sede.Descripcion_Sede AS SEDE, dbo.Local.Nombre_Local AS LOCAL, 
                         dbo.Ubigeo.Distrito + '/ ' + dbo.Ubigeo.Provincia + ' /' + dbo.Ubigeo.Departamento AS [UBICACION LOCAL], dbo.Local.Direccion_Local AS [DIRECCION LOCAL], dbo.Area.Id_Area AS [ID AREA], dbo.Area.Descripcion_Area AS AREA, 
                         dbo.Area.Nro_Piso AS [NRO PISO], dbo.Area.Nro_Ambiente AS [NRO AMBIENTE], dbo.ELEMENTOS_CONFIGURACION.FECHA_REGISTRO AS [FEC. CREACION CI], 
                         dbo.ELEMENTOS_CONFIGURACION.RESPONSABLE_REGISTRO AS [ID RESPONSABLE], dbo.Usuario.Nombre + ' ' + dbo.Usuario.ApePat + ' ' + dbo.Usuario.ApeMat AS RESPONSABLE, 
                         dbo.NIVEL_PRIORIDAD.NOMBRE_NIVEL AS [NIVEL PRIORIDAD], dbo.ELEMENTOS_CONFIGURACION.NRO_SERIE AS [NRO SERIE], 
                         dbo.ELEMENTOS_CONFIGURACION.FABRICANTE_O_PROVEEDOR AS [FABRICANTE / PROVEEDOR], dbo.MARCA.NOMBRE AS MARCA, dbo.MODELO.NOMBRE AS MODELO
FROM            dbo.ELEMENTOS_CONFIGURACION INNER JOIN
                         dbo.TIPOS_ELEMENTO_CONFIGURACION ON dbo.ELEMENTOS_CONFIGURACION.ID_TIPO = dbo.TIPOS_ELEMENTO_CONFIGURACION.ID_TIPO INNER JOIN
                         dbo.ESTADO_ELEMENTO_CONFIGURACION ON dbo.ELEMENTOS_CONFIGURACION.ID_ESTADO = dbo.ESTADO_ELEMENTO_CONFIGURACION.ID_ESTADO INNER JOIN
                         dbo.Personal ON dbo.ELEMENTOS_CONFIGURACION.PROPIETARIO = dbo.Personal.Id_Personal INNER JOIN
                         dbo.[DESCRIPCION_ELEMENTO CONFIGURACION] ON dbo.ELEMENTOS_CONFIGURACION.ID_DESCRIPCION = dbo.[DESCRIPCION_ELEMENTO CONFIGURACION].ID_DESCRIPCION INNER JOIN
                         dbo.IMPACTO_COMERCIAL_ELE_CONF_HAR ON dbo.ELEMENTOS_CONFIGURACION.ID_IMP_ELE_CONF_HAR = dbo.IMPACTO_COMERCIAL_ELE_CONF_HAR.ID_IMP_ELE_CONF_HAR INNER JOIN
                         dbo.Area ON dbo.ELEMENTOS_CONFIGURACION.LOCALIZACION_FISICA = dbo.Area.Id_Area INNER JOIN
                         dbo.Local ON dbo.Area.Id_Local = dbo.Local.Id_Local INNER JOIN
                         dbo.Sede ON dbo.Local.Id_Sede = dbo.Sede.Id_Sede INNER JOIN
                         dbo.Ubigeo ON dbo.Local.Cod_Ubi = dbo.Ubigeo.Cod_Ubi INNER JOIN
                         dbo.Usuario ON dbo.ELEMENTOS_CONFIGURACION.RESPONSABLE_REGISTRO = dbo.Usuario.Id_Uusario INNER JOIN
                         dbo.NIVEL_PRIORIDAD ON dbo.ELEMENTOS_CONFIGURACION.ID_NIVEL = dbo.NIVEL_PRIORIDAD.ID_NIVEL INNER JOIN
                         dbo.MARCA ON dbo.ELEMENTOS_CONFIGURACION.ID_MAR = dbo.MARCA.ID_MAR INNER JOIN
                         dbo.MODELO ON dbo.ELEMENTOS_CONFIGURACION.ID_MOD = dbo.MODELO.ID_MOD




GO
/****** Objeto: View [dbo].[VISTA_CIs_COMPONENTES_ASIGNADOS] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VISTA_CIs_COMPONENTES_ASIGNADOS]
AS
SELECT        dbo.ELEMENTOS_CONFIGURACION.ID_ELEMENTO_CONFIGURACION AS [ID CI], dbo.ELEMENTOS_CONFIGURACION.NOMBRE_ELEMENTO_CONFIGURACION AS [NOMBRE CI], 
                         dbo.TIPOS_ELEMENTO_CONFIGURACION.NOMBRE_TIPO AS [NOMBRE TIPO CI], dbo.ESTADO_ELEMENTO_CONFIGURACION.NOMBRE_ESTADO AS [ESTADO CI], 
                         dbo.Personal.Nombre_Personal + ' ' + dbo.Personal.ApePat_Personal + ' ' + dbo.Personal.ApeMat_Personal AS PROPIETARIO, dbo.[DESCRIPCION_ELEMENTO CONFIGURACION].NOMBRE_DESCRIPCION AS [DESCRIPCION CI], 
                         dbo.IMPACTO_COMERCIAL_ELE_CONF_HAR.NOMBRE AS [IMPACTO CI], dbo.Sede.Descripcion_Sede AS SEDE, dbo.Local.Nombre_Local AS LOCAL, 
                         dbo.Ubigeo.Distrito + '/ ' + dbo.Ubigeo.Provincia + ' /' + dbo.Ubigeo.Departamento AS [UBICACION LOCAL], dbo.Local.Direccion_Local AS [DIRECCION LOCAL], dbo.Area.Descripcion_Area AS AREA, 
                         dbo.Area.Nro_Piso AS [NRO PISO], dbo.Area.Nro_Ambiente AS [NRO AMBIENTE], dbo.ELEMENTOS_CONFIGURACION.FECHA_REGISTRO AS [FEC. CREACION CI], 
                         dbo.Usuario.Nombre + ' ' + dbo.Usuario.ApePat + ' ' + dbo.Usuario.ApeMat AS RESPONSABLE, dbo.NIVEL_PRIORIDAD.NOMBRE_NIVEL AS [NIVEL PRIORIDAD], dbo.ELEMENTOS_CONFIGURACION.NRO_SERIE AS [NRO SERIE], 
                         dbo.ELEMENTOS_CONFIGURACION.FABRICANTE_O_PROVEEDOR AS [FABRICANTE / PROVEEDOR], dbo.MARCA.NOMBRE AS MARCA, dbo.MODELO.NOMBRE AS MODELO, 
                         dbo._CANTIDAD_COMPONENTES_CI(dbo.ELEMENTOS_CONFIGURACION.ID_ELEMENTO_CONFIGURACION) AS [CANTIDAD COMPONENTES], dbo.ELEMENTOS_CONFIGURACION.IP, 
                         dbo.ELEMENTOS_CONFIGURACION.GATEWAY, dbo.ELEMENTOS_CONFIGURACION.GRUPO_TRABAJO AS [GRUPO TRABAJO]
FROM            dbo.ELEMENTOS_CONFIGURACION INNER JOIN
                         dbo.TIPOS_ELEMENTO_CONFIGURACION ON dbo.ELEMENTOS_CONFIGURACION.ID_TIPO = dbo.TIPOS_ELEMENTO_CONFIGURACION.ID_TIPO INNER JOIN
                         dbo.ESTADO_ELEMENTO_CONFIGURACION ON dbo.ELEMENTOS_CONFIGURACION.ID_ESTADO = dbo.ESTADO_ELEMENTO_CONFIGURACION.ID_ESTADO INNER JOIN
                         dbo.Personal ON dbo.ELEMENTOS_CONFIGURACION.PROPIETARIO = dbo.Personal.Id_Personal INNER JOIN
                         dbo.[DESCRIPCION_ELEMENTO CONFIGURACION] ON dbo.ELEMENTOS_CONFIGURACION.ID_DESCRIPCION = dbo.[DESCRIPCION_ELEMENTO CONFIGURACION].ID_DESCRIPCION INNER JOIN
                         dbo.IMPACTO_COMERCIAL_ELE_CONF_HAR ON dbo.ELEMENTOS_CONFIGURACION.ID_IMP_ELE_CONF_HAR = dbo.IMPACTO_COMERCIAL_ELE_CONF_HAR.ID_IMP_ELE_CONF_HAR INNER JOIN
                         dbo.Area ON dbo.ELEMENTOS_CONFIGURACION.LOCALIZACION_FISICA = dbo.Area.Id_Area INNER JOIN
                         dbo.Local ON dbo.Area.Id_Local = dbo.Local.Id_Local INNER JOIN
                         dbo.Sede ON dbo.Local.Id_Sede = dbo.Sede.Id_Sede INNER JOIN
                         dbo.Ubigeo ON dbo.Local.Cod_Ubi = dbo.Ubigeo.Cod_Ubi INNER JOIN
                         dbo.Usuario ON dbo.ELEMENTOS_CONFIGURACION.RESPONSABLE_REGISTRO = dbo.Usuario.Id_Uusario INNER JOIN
                         dbo.NIVEL_PRIORIDAD ON dbo.ELEMENTOS_CONFIGURACION.ID_NIVEL = dbo.NIVEL_PRIORIDAD.ID_NIVEL INNER JOIN
                         dbo.MARCA ON dbo.ELEMENTOS_CONFIGURACION.ID_MAR = dbo.MARCA.ID_MAR INNER JOIN
                         dbo.MODELO ON dbo.ELEMENTOS_CONFIGURACION.ID_MOD = dbo.MODELO.ID_MOD




GO
/****** Objeto: Table [dbo].[COMPONENTES_ELEMENTO_CONFIGURACION] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COMPONENTES_ELEMENTO_CONFIGURACION](
	[ID_COMPONENTE] [int] IDENTITY(1,1) NOT NULL,
	[ID_ELEMENTO_CONFIGURACION] [int] NOT NULL,
	[ID_TIPO_COMPONENTE] [int] NOT NULL,
	[DESCRIPCION] [varchar](max) NOT NULL,
	[FABRICANTE] [varchar](max) NULL,
	[NRO_SERIE] [varchar](max) NULL,
	[ID_MOD] [int] NOT NULL,
	[ID_MAR] [int] NOT NULL,
 CONSTRAINT [PK_COMPONENTES_ELEMENTO_CONFIGURACION] PRIMARY KEY CLUSTERED 
(
	[ID_COMPONENTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[TIPO_COMPONENTE_ELELEMENTO_CONFIGURACION] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPO_COMPONENTE_ELELEMENTO_CONFIGURACION](
	[ID_TIPO_COMPONENTE] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE_TIPO_COMPONENTE] [varchar](max) NOT NULL,
 CONSTRAINT [PK_TIPO_COMPONENTE_ELELEMENTO_CONFIGURACION] PRIMARY KEY CLUSTERED 
(
	[ID_TIPO_COMPONENTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Objeto: View [dbo].[VISTA_DETALLE_CONPONENTES_CIs] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VISTA_DETALLE_CONPONENTES_CIs]
AS
SELECT        dbo.COMPONENTES_ELEMENTO_CONFIGURACION.ID_COMPONENTE AS [ID COMPONENETE], dbo.TIPO_COMPONENTE_ELELEMENTO_CONFIGURACION.NOMBRE_TIPO_COMPONENTE AS [TIPO COMPONENTE], 
                         dbo.COMPONENTES_ELEMENTO_CONFIGURACION.DESCRIPCION, dbo.COMPONENTES_ELEMENTO_CONFIGURACION.FABRICANTE, dbo.COMPONENTES_ELEMENTO_CONFIGURACION.NRO_SERIE AS [NRO SERIE], 
                         dbo.MODELO.NOMBRE AS MODELO, dbo.MARCA.NOMBRE AS MARCA, dbo.COMPONENTES_ELEMENTO_CONFIGURACION.ID_ELEMENTO_CONFIGURACION AS [ID CI]
FROM            dbo.COMPONENTES_ELEMENTO_CONFIGURACION INNER JOIN
                         dbo.TIPO_COMPONENTE_ELELEMENTO_CONFIGURACION ON 
                         dbo.COMPONENTES_ELEMENTO_CONFIGURACION.ID_TIPO_COMPONENTE = dbo.TIPO_COMPONENTE_ELELEMENTO_CONFIGURACION.ID_TIPO_COMPONENTE INNER JOIN
                         dbo.MODELO ON dbo.COMPONENTES_ELEMENTO_CONFIGURACION.ID_MOD = dbo.MODELO.ID_MOD INNER JOIN
                         dbo.MARCA ON dbo.COMPONENTES_ELEMENTO_CONFIGURACION.ID_MAR = dbo.MARCA.ID_MAR


GO
/****** Objeto: View [dbo].[VISTA_ELEMENTOS_CONFIGURACION] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VISTA_ELEMENTOS_CONFIGURACION]
AS
SELECT        dbo.ELEMENTOS_CONFIGURACION.ID_ELEMENTO_CONFIGURACION AS [ID CI], dbo.ELEMENTOS_CONFIGURACION.NOMBRE_ELEMENTO_CONFIGURACION AS [NOMBRE CI], 
                         dbo.TIPOS_ELEMENTO_CONFIGURACION.ID_TIPO AS [ID TIPO CI], dbo.TIPOS_ELEMENTO_CONFIGURACION.NOMBRE_TIPO AS [NOMBRE TIPO CI], 
                         dbo.ESTADO_ELEMENTO_CONFIGURACION.NOMBRE_ESTADO AS [ESTADO CI], dbo.Personal.Id_Personal AS [ID PROPIETARIO], 
                         dbo.Personal.Nombre_Personal + ' ' + dbo.Personal.ApePat_Personal + ' ' + dbo.Personal.ApeMat_Personal AS PROPIETARIO, dbo.[DESCRIPCION_ELEMENTO CONFIGURACION].NOMBRE_DESCRIPCION AS [DESCRIPCION CI], 
                         dbo.IMPACTO_COMERCIAL_ELE_CONF_HAR.NOMBRE AS [IMPACTO CI], dbo.Sede.Descripcion_Sede AS SEDE, dbo.Local.Nombre_Local AS LOCAL, 
                         dbo.Ubigeo.Distrito + '/ ' + dbo.Ubigeo.Provincia + ' /' + dbo.Ubigeo.Departamento AS [UBICACION LOCAL], dbo.Local.Direccion_Local AS [DIRECCION LOCAL], dbo.Area.Id_Area AS [ID AREA], dbo.Area.Descripcion_Area AS AREA, 
                         dbo.Area.Nro_Piso AS [NRO PISO], dbo.Area.Nro_Ambiente AS [NRO AMBIENTE], dbo.ELEMENTOS_CONFIGURACION.FECHA_REGISTRO AS [FEC. CREACION CI], 
                         dbo.ELEMENTOS_CONFIGURACION.RESPONSABLE_REGISTRO AS [ID RESPONSABLE], dbo.Usuario.Nombre + ' ' + dbo.Usuario.ApePat + ' ' + dbo.Usuario.ApeMat AS RESPONSABLE, 
                         dbo.NIVEL_PRIORIDAD.NOMBRE_NIVEL AS [NIVEL PRIORIDAD], dbo.ELEMENTOS_CONFIGURACION.NRO_SERIE AS [NRO SERIE], 
                         dbo.ELEMENTOS_CONFIGURACION.FABRICANTE_O_PROVEEDOR AS [FABRICANTE / PROVEEDOR], dbo.MARCA.NOMBRE AS MARCA, dbo.MODELO.NOMBRE AS MODELO, dbo.ELEMENTOS_CONFIGURACION.IP, 
                         dbo.ELEMENTOS_CONFIGURACION.GATEWAY, dbo.ELEMENTOS_CONFIGURACION.GRUPO_TRABAJO AS [GRUPO TRABAJO]
FROM            dbo.ELEMENTOS_CONFIGURACION INNER JOIN
                         dbo.TIPOS_ELEMENTO_CONFIGURACION ON dbo.ELEMENTOS_CONFIGURACION.ID_TIPO = dbo.TIPOS_ELEMENTO_CONFIGURACION.ID_TIPO INNER JOIN
                         dbo.ESTADO_ELEMENTO_CONFIGURACION ON dbo.ELEMENTOS_CONFIGURACION.ID_ESTADO = dbo.ESTADO_ELEMENTO_CONFIGURACION.ID_ESTADO INNER JOIN
                         dbo.Personal ON dbo.ELEMENTOS_CONFIGURACION.PROPIETARIO = dbo.Personal.Id_Personal INNER JOIN
                         dbo.[DESCRIPCION_ELEMENTO CONFIGURACION] ON dbo.ELEMENTOS_CONFIGURACION.ID_DESCRIPCION = dbo.[DESCRIPCION_ELEMENTO CONFIGURACION].ID_DESCRIPCION INNER JOIN
                         dbo.IMPACTO_COMERCIAL_ELE_CONF_HAR ON dbo.ELEMENTOS_CONFIGURACION.ID_IMP_ELE_CONF_HAR = dbo.IMPACTO_COMERCIAL_ELE_CONF_HAR.ID_IMP_ELE_CONF_HAR INNER JOIN
                         dbo.Area ON dbo.ELEMENTOS_CONFIGURACION.LOCALIZACION_FISICA = dbo.Area.Id_Area INNER JOIN
                         dbo.Local ON dbo.Area.Id_Local = dbo.Local.Id_Local INNER JOIN
                         dbo.Sede ON dbo.Local.Id_Sede = dbo.Sede.Id_Sede INNER JOIN
                         dbo.Ubigeo ON dbo.Local.Cod_Ubi = dbo.Ubigeo.Cod_Ubi INNER JOIN
                         dbo.Usuario ON dbo.ELEMENTOS_CONFIGURACION.RESPONSABLE_REGISTRO = dbo.Usuario.Id_Uusario INNER JOIN
                         dbo.NIVEL_PRIORIDAD ON dbo.ELEMENTOS_CONFIGURACION.ID_NIVEL = dbo.NIVEL_PRIORIDAD.ID_NIVEL INNER JOIN
                         dbo.MARCA ON dbo.ELEMENTOS_CONFIGURACION.ID_MAR = dbo.MARCA.ID_MAR INNER JOIN
                         dbo.MODELO ON dbo.ELEMENTOS_CONFIGURACION.ID_MOD = dbo.MODELO.ID_MOD




GO
/****** Objeto: View [dbo].[VISTA_ELEMENTOS_CONFIGURACION_2] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VISTA_ELEMENTOS_CONFIGURACION_2]
AS
SELECT        dbo.ELEMENTOS_CONFIGURACION.ID_ELEMENTO_CONFIGURACION AS [ID CI], 
                         dbo.ELEMENTOS_CONFIGURACION.NOMBRE_ELEMENTO_CONFIGURACION AS [NOMBRE CI], 
                         dbo.TIPOS_ELEMENTO_CONFIGURACION.ID_TIPO AS [ID TIPO CI], dbo.TIPOS_ELEMENTO_CONFIGURACION.NOMBRE_TIPO AS [NOMBRE TIPO CI], 
                         dbo.ESTADO_ELEMENTO_CONFIGURACION.NOMBRE_ESTADO AS [ESTADO CI], dbo.Personal.Id_Personal AS [ID PROPIETARIO], 
                         dbo.Personal.Nombre_Personal + ' ' + dbo.Personal.ApePat_Personal + ' ' + dbo.Personal.ApeMat_Personal AS PROPIETARIO, 
                         dbo.[DESCRIPCION_ELEMENTO CONFIGURACION].NOMBRE_DESCRIPCION AS [DESCRIPCION CI], 
                         dbo.IMPACTO_COMERCIAL_ELE_CONF_HAR.NOMBRE AS [IMPACTO CI], dbo.Sede.Descripcion_Sede AS SEDE, dbo.Local.Nombre_Local AS LOCAL, 
                         dbo.Ubigeo.Distrito + '/ ' + dbo.Ubigeo.Provincia + ' /' + dbo.Ubigeo.Departamento AS [UBICACION LOCAL], dbo.Local.Direccion_Local AS [DIRECCION LOCAL], 
                         dbo.Area.Id_Area AS [ID AREA], dbo.Area.Descripcion_Area AS AREA, dbo.Area.Nro_Piso AS [NRO PISO], dbo.Area.Nro_Ambiente AS [NRO AMBIENTE], 
                         dbo.ELEMENTOS_CONFIGURACION.FECHA_REGISTRO AS [FEC. CREACION CI], 
                         dbo.ELEMENTOS_CONFIGURACION.RESPONSABLE_REGISTRO AS [ID RESPONSABLE], 
                         dbo.Usuario.Nombre + ' ' + dbo.Usuario.ApePat + ' ' + dbo.Usuario.ApeMat AS RESPONSABLE, 
                         dbo.NIVEL_PRIORIDAD.NOMBRE_NIVEL AS [NIVEL PRIORIDAD], dbo.ELEMENTOS_CONFIGURACION.NRO_SERIE AS [NRO SERIE], 
                         dbo.ELEMENTOS_CONFIGURACION.FABRICANTE_O_PROVEEDOR AS [FABRICANTE / PROVEEDOR], dbo.MARCA.NOMBRE AS MARCA, 
                         dbo.MODELO.NOMBRE AS MODELO
FROM            dbo.ELEMENTOS_CONFIGURACION INNER JOIN
                         dbo.TIPOS_ELEMENTO_CONFIGURACION ON dbo.ELEMENTOS_CONFIGURACION.ID_TIPO = dbo.TIPOS_ELEMENTO_CONFIGURACION.ID_TIPO INNER JOIN
                         dbo.ESTADO_ELEMENTO_CONFIGURACION ON 
                         dbo.ELEMENTOS_CONFIGURACION.ID_ESTADO = dbo.ESTADO_ELEMENTO_CONFIGURACION.ID_ESTADO INNER JOIN
                         dbo.Personal ON dbo.ELEMENTOS_CONFIGURACION.PROPIETARIO = dbo.Personal.Id_Personal INNER JOIN
                         dbo.[DESCRIPCION_ELEMENTO CONFIGURACION] ON 
                         dbo.ELEMENTOS_CONFIGURACION.ID_DESCRIPCION = dbo.[DESCRIPCION_ELEMENTO CONFIGURACION].ID_DESCRIPCION INNER JOIN
                         dbo.IMPACTO_COMERCIAL_ELE_CONF_HAR ON 
                         dbo.ELEMENTOS_CONFIGURACION.ID_IMP_ELE_CONF_HAR = dbo.IMPACTO_COMERCIAL_ELE_CONF_HAR.ID_IMP_ELE_CONF_HAR INNER JOIN
                         dbo.Area ON dbo.ELEMENTOS_CONFIGURACION.LOCALIZACION_FISICA = dbo.Area.Id_Area AND dbo.Personal.Id_Area = dbo.Area.Id_Area INNER JOIN
                         dbo.Local ON dbo.Area.Id_Local = dbo.Local.Id_Local INNER JOIN
                         dbo.Sede ON dbo.Local.Id_Sede = dbo.Sede.Id_Sede INNER JOIN
                         dbo.Ubigeo ON dbo.Local.Cod_Ubi = dbo.Ubigeo.Cod_Ubi INNER JOIN
                         dbo.Usuario ON dbo.ELEMENTOS_CONFIGURACION.RESPONSABLE_REGISTRO = dbo.Usuario.Id_Uusario INNER JOIN
                         dbo.NIVEL_PRIORIDAD ON dbo.ELEMENTOS_CONFIGURACION.ID_NIVEL = dbo.NIVEL_PRIORIDAD.ID_NIVEL INNER JOIN
                         dbo.MARCA ON dbo.ELEMENTOS_CONFIGURACION.ID_MAR = dbo.MARCA.ID_MAR INNER JOIN
                         dbo.MODELO ON dbo.ELEMENTOS_CONFIGURACION.ID_MOD = dbo.MODELO.ID_MOD





GO
/****** Objeto: View [dbo].[VISTA_LICENCIAS] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VISTA_LICENCIAS]
AS
SELECT        dbo.LICENCIA_ELEMENTO_CONFIGURACION.ID_LICENCIA_ELE_CONF AS [ID LI], 
                         dbo.TIPO_LICENCIA_ELEMENTO_CONFIGURACION.NOMBRE_LICENCIA_CI AS LICENCIA, dbo.LICENCIA_ELEMENTO_CONFIGURACION.NOMBRE, 
                         dbo.LICENCIA_ELEMENTO_CONFIGURACION.VERSION, 
                         dbo.[SUSCRIPCION_LICENCIA-ELEMENTO_CONFIGURACION].NOMBRE_SUSCRIPCION_LICENCIA_CI AS SUSCRIPCION, 
                         dbo.LICENCIA_ELEMENTO_CONFIGURACION.FECHA_INICIO AS [FEC. INI.], dbo.LICENCIA_ELEMENTO_CONFIGURACION.FECHA_FIN AS [FEC. FIN], 
                         CASE dbo.LICENCIA_ELEMENTO_CONFIGURACION.LICENCIA_PERPETUA WHEN 1 THEN 'SI' ELSE 'NO' END AS PERPETUA, 
                         dbo.LICENCIA_ELEMENTO_CONFIGURACION.DESCRIPCION, 
                         dbo._VERIFICA_VENCIMIENTO_LICENCIA(dbo.LICENCIA_ELEMENTO_CONFIGURACION.LICENCIA_PERPETUA, 
                         dbo.LICENCIA_ELEMENTO_CONFIGURACION.FECHA_FIN) AS [VENCE LICENCIA]
FROM            dbo.LICENCIA_ELEMENTO_CONFIGURACION INNER JOIN
                         dbo.TIPO_LICENCIA_ELEMENTO_CONFIGURACION ON 
                         dbo.LICENCIA_ELEMENTO_CONFIGURACION.ID_TIPO_LICENCIA_CI = dbo.TIPO_LICENCIA_ELEMENTO_CONFIGURACION.ID_TIPO_LICENCIA_CI INNER JOIN
                         dbo.[SUSCRIPCION_LICENCIA-ELEMENTO_CONFIGURACION] ON 
                         dbo.LICENCIA_ELEMENTO_CONFIGURACION.ID_SUSCRIPCION_LICENCIA_CI = dbo.[SUSCRIPCION_LICENCIA-ELEMENTO_CONFIGURACION].ID_SUSCRIPCION_LICENCIA_CI
                          AND 
                         dbo.TIPO_LICENCIA_ELEMENTO_CONFIGURACION.ID_TIPO_LICENCIA_CI = dbo.[SUSCRIPCION_LICENCIA-ELEMENTO_CONFIGURACION].ID_TIPO_LICENCIA_CI





GO
/****** Objeto: View [dbo].[VISTA_LICENCIAS_2] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VISTA_LICENCIAS_2]
AS
SELECT        dbo.OBTENER_UBICACION_LICENCIA_AREA(dbo.LICENCIA_ELEMENTO_CONFIGURACION.ID_LICENCIA_ELE_CONF, 
                         dbo.TIPO_LICENCIA_ELEMENTO_CONFIGURACION.NOMBRE_LICENCIA_CI, dbo.LICENCIA_ELEMENTO_CONFIGURACION.NOMBRE) AS AREA, 
                         dbo.TIPO_LICENCIA_ELEMENTO_CONFIGURACION.NOMBRE_LICENCIA_CI AS LICENCIA, dbo.LICENCIA_ELEMENTO_CONFIGURACION.NOMBRE, 
                         dbo.LICENCIA_ELEMENTO_CONFIGURACION.VERSION, 
                         dbo.[SUSCRIPCION_LICENCIA-ELEMENTO_CONFIGURACION].NOMBRE_SUSCRIPCION_LICENCIA_CI AS SUSCRIPCION, 
                         dbo.LICENCIA_ELEMENTO_CONFIGURACION.FECHA_INICIO AS [FEC. INI.], dbo.LICENCIA_ELEMENTO_CONFIGURACION.FECHA_FIN AS [FEC. FIN], 
                         CASE dbo.LICENCIA_ELEMENTO_CONFIGURACION.LICENCIA_PERPETUA WHEN 1 THEN 'SI' ELSE 'NO' END AS PERPETUA, 
                         dbo.LICENCIA_ELEMENTO_CONFIGURACION.DESCRIPCION, 
                         dbo._VERIFICA_VENCIMIENTO_LICENCIA(dbo.LICENCIA_ELEMENTO_CONFIGURACION.LICENCIA_PERPETUA, 
                         dbo.LICENCIA_ELEMENTO_CONFIGURACION.FECHA_FIN) AS [VENCE LICENCIA]
FROM            dbo.LICENCIA_ELEMENTO_CONFIGURACION INNER JOIN
                         dbo.TIPO_LICENCIA_ELEMENTO_CONFIGURACION ON 
                         dbo.LICENCIA_ELEMENTO_CONFIGURACION.ID_TIPO_LICENCIA_CI = dbo.TIPO_LICENCIA_ELEMENTO_CONFIGURACION.ID_TIPO_LICENCIA_CI INNER JOIN
                         dbo.[SUSCRIPCION_LICENCIA-ELEMENTO_CONFIGURACION] ON 
                         dbo.LICENCIA_ELEMENTO_CONFIGURACION.ID_SUSCRIPCION_LICENCIA_CI = dbo.[SUSCRIPCION_LICENCIA-ELEMENTO_CONFIGURACION].ID_SUSCRIPCION_LICENCIA_CI
                          AND 
                         dbo.TIPO_LICENCIA_ELEMENTO_CONFIGURACION.ID_TIPO_LICENCIA_CI = dbo.[SUSCRIPCION_LICENCIA-ELEMENTO_CONFIGURACION].ID_TIPO_LICENCIA_CI





GO
/****** Objeto: View [dbo].[VISTA_LOCALES] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VISTA_LOCALES]
AS
SELECT        dbo.Local.Id_Local AS [ID LOCAL], dbo.Local.Codigo_Local AS [LOCAL CODIGO], dbo.Local.Nombre_Local AS [LOCAL NOMBRE], 
                         dbo.Local.Direccion_Local AS [LOCAL DIRECCION], dbo.Sede.Descripcion_Sede AS SEDE, dbo.Ubigeo.Cod_Ubi AS [ID UBI], 
                         dbo.Ubigeo.Departamento + ' / ' + dbo.Ubigeo.Provincia + ' / ' + dbo.Ubigeo.Distrito AS [UBICACION GEOGRAFICA], dbo.Local.Telefono_local AS TELEFONO, 
                         dbo.Local.Pagnia_Web_Local AS [PAGINA WEB], dbo.Local.Email_Local AS EMAIL, dbo.Local.Total_CIS_Local AS [TOTAL CIS]
FROM            dbo.Sede INNER JOIN
                         dbo.Local ON dbo.Sede.Id_Sede = dbo.Local.Id_Sede INNER JOIN
                         dbo.Ubigeo ON dbo.Local.Cod_Ubi = dbo.Ubigeo.Cod_Ubi





GO
/****** Objeto: Table [dbo].[CARGO] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CARGO](
	[ID_CARGO] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE_CARGO] [varchar](max) NOT NULL,
 CONSTRAINT [PK_CARGO] PRIMARY KEY CLUSTERED 
(
	[ID_CARGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[Dependencia] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Dependencia](
	[Id_Dependencia] [int] IDENTITY(1,1) NOT NULL,
	[Codigo_Depemdencia] [varchar](4) NOT NULL,
	[Nombre_Dependencia] [varchar](max) NOT NULL,
 CONSTRAINT [PK_Dependencia] PRIMARY KEY CLUSTERED 
(
	[Id_Dependencia] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[Profesion_Ocupacion] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Profesion_Ocupacion](
	[Id_prof_ocup] [int] IDENTITY(1,1) NOT NULL,
	[Prof_Ocup] [varchar](250) NOT NULL,
	[Descripcion_prof_ocup] [varchar](250) NULL,
 CONSTRAINT [PK_Profes_Ocupac] PRIMARY KEY CLUSTERED 
(
	[Id_prof_ocup] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[Tipo_de_Documento_de_Identidad] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tipo_de_Documento_de_Identidad](
	[Id_Tipo_Documento] [int] IDENTITY(1,1) NOT NULL,
	[Codigo_Tipo_Documento] [varchar](50) NOT NULL,
	[Nombre_Tipo_Documento] [varchar](250) NOT NULL,
	[Siglas_Tipo_Documento] [varchar](50) NULL,
	[Descrip_Tipo_Documento] [varchar](200) NULL,
 CONSTRAINT [PK_Tipo_de_Documento_de_Identidad] PRIMARY KEY CLUSTERED 
(
	[Id_Tipo_Documento] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: View [dbo].[VISTA_PERSONAL] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VISTA_PERSONAL]
AS
SELECT        dbo.Personal.Id_Personal, dbo.Sede.Descripcion_Sede AS SEDE, dbo.Local.Nombre_Local AS LOCAL, dbo.Area.Descripcion_Area AS AREA, 
                         dbo.Dependencia.Nombre_Dependencia AS DEPENDENCIA, dbo.Personal.Codigo_Personal AS CODIGO, dbo.Personal.Nombre_Personal AS NOMBRE, 
                         dbo.Personal.ApePat_Personal AS [APELLIDO PATERNO], dbo.Personal.ApeMat_Personal AS [APELLIDO MATERNO], 
                         dbo.Tipo_de_Documento_de_Identidad.Nombre_Tipo_Documento AS [TIPO DOC. IDENT.], dbo.Personal.Nro_Dni_Personal AS [NRO. DOC. IDENT.], 
                         dbo.Profesion_Ocupacion.Prof_Ocup AS PROFESION, dbo.Personal.Tel_Personal AS TELEFONO, dbo.Personal.Email_Personal AS EMAIL, 
                         CASE dbo.Personal.Estado_Personal WHEN 1 THEN 'ACTIVO' ELSE 'INACTIVO' END AS ESTADO, dbo.CARGO.NOMBRE_CARGO AS CARGO
FROM            dbo.Personal INNER JOIN
                         dbo.Tipo_de_Documento_de_Identidad ON dbo.Personal.Id_Tipo_Documento = dbo.Tipo_de_Documento_de_Identidad.Id_Tipo_Documento INNER JOIN
                         dbo.Profesion_Ocupacion ON dbo.Personal.Id_prof_ocup = dbo.Profesion_Ocupacion.Id_prof_ocup INNER JOIN
                         dbo.Area ON dbo.Personal.Id_Area = dbo.Area.Id_Area INNER JOIN
                         dbo.Dependencia ON dbo.Personal.Id_Dependencia = dbo.Dependencia.Id_Dependencia INNER JOIN
                         dbo.Local ON dbo.Area.Id_Local = dbo.Local.Id_Local INNER JOIN
                         dbo.Sede ON dbo.Local.Id_Sede = dbo.Sede.Id_Sede INNER JOIN
                         dbo.CARGO ON dbo.Personal.ID_CARGO = dbo.CARGO.ID_CARGO





GO
/****** Objeto: View [dbo].[VISTA_PERSONAL_2] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VISTA_PERSONAL_2]
AS
SELECT        dbo.Personal.Id_Personal AS ID, dbo.Sede.Descripcion_Sede AS SEDE, dbo.Local.Nombre_Local AS LOCAL, dbo.Area.Descripcion_Area AS AREA, 
                         dbo.Dependencia.Nombre_Dependencia AS DEPENDENCIA, dbo.Area.Nro_Piso AS [NRO PISO], dbo.Area.Nro_Ambiente AS [NRO AMBIENTE], 
                         dbo.Personal.Nombre_Personal + ' ' + dbo.Personal.ApePat_Personal + ' ' + dbo.Personal.ApeMat_Personal AS PERSONAL, 
                         dbo.Profesion_Ocupacion.Prof_Ocup AS PROFESION, dbo.Personal.Tel_Personal AS TELEFONO, dbo.Personal.Email_Personal AS EMAIL, 
                         CASE dbo.Personal.Estado_Personal WHEN 1 THEN 'ACTIVO' ELSE 'INACTIVO' END AS ESTADO
FROM            dbo.Personal INNER JOIN
                         dbo.Tipo_de_Documento_de_Identidad ON dbo.Personal.Id_Tipo_Documento = dbo.Tipo_de_Documento_de_Identidad.Id_Tipo_Documento INNER JOIN
                         dbo.Profesion_Ocupacion ON dbo.Personal.Id_prof_ocup = dbo.Profesion_Ocupacion.Id_prof_ocup INNER JOIN
                         dbo.Area ON dbo.Personal.Id_Area = dbo.Area.Id_Area INNER JOIN
                         dbo.Dependencia ON dbo.Personal.Id_Dependencia = dbo.Dependencia.Id_Dependencia INNER JOIN
                         dbo.Local ON dbo.Area.Id_Local = dbo.Local.Id_Local INNER JOIN
                         dbo.Sede ON dbo.Local.Id_Sede = dbo.Sede.Id_Sede
WHERE        (CASE dbo.Personal.Estado_Personal WHEN 1 THEN 'ACTIVO' ELSE 'INACTIVO' END = 'ACTIVO')





GO
/****** Objeto: Table [dbo].[RELACION_ELEMENTO_CONFIGURACION] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RELACION_ELEMENTO_CONFIGURACION](
	[ID_RELACION] [int] IDENTITY(1,1) NOT NULL,
	[ELEMENTO_CONFIGURACION_PADRE] [int] NOT NULL,
	[ELEMENTO_CONFIGURACION_HIJO] [int] NOT NULL,
	[COD_TIPO_RELA] [int] NOT NULL,
 CONSTRAINT [PK_RELACION_ELEMENTO_CONFIGURACION] PRIMARY KEY CLUSTERED 
(
	[ID_RELACION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[TIPO_RELACION_ELEMENTO_CONFIGURACION] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPO_RELACION_ELEMENTO_CONFIGURACION](
	[COD_TIPO_RELA] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE_TIPO_RELA] [varchar](25) NOT NULL,
 CONSTRAINT [PK_TIPO_RELACION_ELEMENTO_CONFIGURACION] PRIMARY KEY CLUSTERED 
(
	[COD_TIPO_RELA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: View [dbo].[VISTA_PORCENTAJE_DE_CIS_RELATIVO_A_SERVICIOS] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VISTA_PORCENTAJE_DE_CIS_RELATIVO_A_SERVICIOS]
AS
SELECT        R.ID_RELACION, P.ID_ELEMENTO_CONFIGURACION AS [PADRE ID], P.NOMBRE_ELEMENTO_CONFIGURACION AS [PADRE CI], 
                         dbo.TIPOS_ELEMENTO_CONFIGURACION.NOMBRE_TIPO AS [PADRE TIPO CI], 
                         dbo.ESTADO_ELEMENTO_CONFIGURACION.NOMBRE_ESTADO AS [PADRE ESTADO CI], 
                         dbo.Personal.Nombre_Personal + ' ' + dbo.Personal.ApePat_Personal + ' ' + dbo.Personal.ApeMat_Personal AS [PADRE PROPIETARIO CI], 
                         dbo.[DESCRIPCION_ELEMENTO CONFIGURACION].NOMBRE_DESCRIPCION AS [PADRE DESCRIPCION CI], 
                         dbo.NIVEL_PRIORIDAD.NOMBRE_NIVEL AS [PADRE NIVEL PRIORIDAD], dbo.Sede.Descripcion_Sede AS [PADRE SEDE], 
                         dbo.Local.Nombre_Local AS [PADRE LOCAL], dbo.Area.Descripcion_Area AS [PADRE AREA], dbo.Area.Nro_Piso AS [PADRE NRO PISO], 
                         dbo.Area.Nro_Ambiente AS [PADRE NRO AMBIENTE], dbo.Ubigeo.Distrito + ' ' + dbo.Ubigeo.Provincia + ' ' + dbo.Ubigeo.Departamento AS [PADRE UBICACION],
                          dbo.Local.Direccion_Local AS [PADRE DIRECCION LOCAL], C.ID_ELEMENTO_CONFIGURACION AS [HIJO ID], 
                         C.NOMBRE_ELEMENTO_CONFIGURACION AS [HIJO CI], TIPOS_ELEMENTO_CONFIGURACION_1.NOMBRE_TIPO AS [HIJO TIPO CI], 
                         ESTADO_ELEMENTO_CONFIGURACION_1.NOMBRE_ESTADO AS [HIJO ESTADO CI], 
                         Personal_1.Nombre_Personal + ' ' + Personal_1.ApePat_Personal + ' ' + Personal_1.ApeMat_Personal AS [HIJO PROPIETARIO CI], 
                         [DESCRIPCION_ELEMENTO CONFIGURACION_1].NOMBRE_DESCRIPCION AS [HIJO DESCRIPCION CI], 
                         NIVEL_PRIORIDAD_1.NOMBRE_NIVEL AS [HIJO NIVEL PRIORIDAD], Sede_1.Descripcion_Sede AS [HIJO SEDE], Local_1.Nombre_Local AS [HIJO LOCAL], 
                         Area_1.Descripcion_Area AS [HIJO AREA], Area_1.Nro_Piso AS [HIJO NRO PISO], Area_1.Nro_Ambiente AS [HIJO NRO AMBIENTE], 
                         Ubigeo_1.Distrito + ' ' + Ubigeo_1.Provincia + ' ' + Ubigeo_1.Departamento AS [HIJO UBICACION], Local_1.Direccion_Local AS [HIJO DIRECCION LOCAL], 
                         dbo.TIPO_RELACION_ELEMENTO_CONFIGURACION.NOMBRE_TIPO_RELA AS [TIPO RELACION], P.NRO_SERIE AS [PADRE NRO SERIE], 
                         C.NRO_SERIE AS [HIJO NRO SERIE], P.FABRICANTE_O_PROVEEDOR AS [PADRE FABICANTE / PROVEEDOR], 
                         C.FABRICANTE_O_PROVEEDOR AS [HIJO FABRICANTE / PROVEEDOR], P.IP AS [PADRE IP], P.GATEWAY AS [PADRE GATEWAY], C.IP AS [HIJO IP], 
                         C.GATEWAY AS [HIJO GATEWAY], P.GRUPO_TRABAJO AS [PADRE GRUPO TRABAJO], C.GRUPO_TRABAJO AS [HIJO GRUPO TRABAJO]
FROM            dbo.RELACION_ELEMENTO_CONFIGURACION AS R INNER JOIN
                         dbo.ELEMENTOS_CONFIGURACION AS P ON R.ELEMENTO_CONFIGURACION_PADRE = P.ID_ELEMENTO_CONFIGURACION INNER JOIN
                         dbo.ELEMENTOS_CONFIGURACION AS C ON R.ELEMENTO_CONFIGURACION_HIJO = C.ID_ELEMENTO_CONFIGURACION INNER JOIN
                         dbo.TIPO_RELACION_ELEMENTO_CONFIGURACION ON 
                         R.COD_TIPO_RELA = dbo.TIPO_RELACION_ELEMENTO_CONFIGURACION.COD_TIPO_RELA INNER JOIN
                         dbo.TIPOS_ELEMENTO_CONFIGURACION ON P.ID_TIPO = dbo.TIPOS_ELEMENTO_CONFIGURACION.ID_TIPO INNER JOIN
                         dbo.TIPOS_ELEMENTO_CONFIGURACION AS TIPOS_ELEMENTO_CONFIGURACION_1 ON 
                         C.ID_TIPO = TIPOS_ELEMENTO_CONFIGURACION_1.ID_TIPO INNER JOIN
                         dbo.ESTADO_ELEMENTO_CONFIGURACION ON P.ID_ESTADO = dbo.ESTADO_ELEMENTO_CONFIGURACION.ID_ESTADO INNER JOIN
                         dbo.ESTADO_ELEMENTO_CONFIGURACION AS ESTADO_ELEMENTO_CONFIGURACION_1 ON 
                         C.ID_ESTADO = ESTADO_ELEMENTO_CONFIGURACION_1.ID_ESTADO INNER JOIN
                         dbo.Personal ON P.PROPIETARIO = dbo.Personal.Id_Personal INNER JOIN
                         dbo.Personal AS Personal_1 ON C.PROPIETARIO = Personal_1.Id_Personal INNER JOIN
                         dbo.[DESCRIPCION_ELEMENTO CONFIGURACION] ON P.ID_DESCRIPCION = dbo.[DESCRIPCION_ELEMENTO CONFIGURACION].ID_DESCRIPCION INNER JOIN
                         dbo.[DESCRIPCION_ELEMENTO CONFIGURACION] AS [DESCRIPCION_ELEMENTO CONFIGURACION_1] ON 
                         C.ID_DESCRIPCION = [DESCRIPCION_ELEMENTO CONFIGURACION_1].ID_DESCRIPCION INNER JOIN
                         dbo.NIVEL_PRIORIDAD ON P.ID_NIVEL = dbo.NIVEL_PRIORIDAD.ID_NIVEL INNER JOIN
                         dbo.NIVEL_PRIORIDAD AS NIVEL_PRIORIDAD_1 ON C.ID_NIVEL = NIVEL_PRIORIDAD_1.ID_NIVEL INNER JOIN
                         dbo.Area ON P.LOCALIZACION_FISICA = dbo.Area.Id_Area INNER JOIN
                         dbo.Local ON dbo.Area.Id_Local = dbo.Local.Id_Local INNER JOIN
                         dbo.Sede ON dbo.Local.Id_Sede = dbo.Sede.Id_Sede INNER JOIN
                         dbo.Ubigeo ON dbo.Local.Cod_Ubi = dbo.Ubigeo.Cod_Ubi INNER JOIN
                         dbo.Area AS Area_1 ON C.LOCALIZACION_FISICA = Area_1.Id_Area INNER JOIN
                         dbo.Local AS Local_1 ON Area_1.Id_Local = Local_1.Id_Local INNER JOIN
                         dbo.Sede AS Sede_1 ON Local_1.Id_Sede = Sede_1.Id_Sede INNER JOIN
                         dbo.Ubigeo AS Ubigeo_1 ON Local_1.Cod_Ubi = Ubigeo_1.Cod_Ubi
WHERE        (TIPOS_ELEMENTO_CONFIGURACION_1.NOMBRE_TIPO = 'SERVICIOS AL CIUDADANO') OR
                         (TIPOS_ELEMENTO_CONFIGURACION_1.NOMBRE_TIPO = 'SERVICIOS AL PROFESIONAL')





GO
/****** Objeto: View [dbo].[VISTA_RELACION_CI_CON_OTROS_CIS] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VISTA_RELACION_CI_CON_OTROS_CIS]
AS
SELECT        R.ID_RELACION, P.ID_ELEMENTO_CONFIGURACION AS [PADRE ID], P.NOMBRE_ELEMENTO_CONFIGURACION AS [PADRE CI], 
                         dbo.TIPOS_ELEMENTO_CONFIGURACION.NOMBRE_TIPO AS [PADRE TIPO CI], 
                         dbo.ESTADO_ELEMENTO_CONFIGURACION.NOMBRE_ESTADO AS [PADRE ESTADO CI], 
                         dbo.Personal.Nombre_Personal + ' ' + dbo.Personal.ApePat_Personal + ' ' + dbo.Personal.ApeMat_Personal AS [PADRE PROPIETARIO CI], 
                         dbo.[DESCRIPCION_ELEMENTO CONFIGURACION].NOMBRE_DESCRIPCION AS [PADRE DESCRIPCION CI], 
                         dbo.NIVEL_PRIORIDAD.NOMBRE_NIVEL AS [PADRE NIVEL PRIORIDAD], dbo.Sede.Descripcion_Sede AS [PADRE SEDE], 
                         dbo.Local.Nombre_Local AS [PADRE LOCAL], dbo.Area.Descripcion_Area AS [PADRE AREA], dbo.Area.Nro_Piso AS [PADRE NRO PISO], 
                         dbo.Area.Nro_Ambiente AS [PADRE NRO AMBIENTE], dbo.Ubigeo.Distrito + ' ' + dbo.Ubigeo.Provincia + ' ' + dbo.Ubigeo.Departamento AS [PADRE UBICACION],
                          dbo.Local.Direccion_Local AS [PADRE DIRECCION LOCAL], C.ID_ELEMENTO_CONFIGURACION AS [HIJO ID], 
                         C.NOMBRE_ELEMENTO_CONFIGURACION AS [HIJO CI], TIPOS_ELEMENTO_CONFIGURACION_1.NOMBRE_TIPO AS [HIJO TIPO CI], 
                         ESTADO_ELEMENTO_CONFIGURACION_1.NOMBRE_ESTADO AS [HIJO ESTADO CI], 
                         Personal_1.Nombre_Personal + ' ' + Personal_1.ApePat_Personal + ' ' + Personal_1.ApeMat_Personal AS [HIJO PROPIETARIO CI], 
                         [DESCRIPCION_ELEMENTO CONFIGURACION_1].NOMBRE_DESCRIPCION AS [HIJO DESCRIPCION CI], 
                         NIVEL_PRIORIDAD_1.NOMBRE_NIVEL AS [HIJO NIVEL PRIORIDAD], Sede_1.Descripcion_Sede AS [HIJO SEDE], Local_1.Nombre_Local AS [HIJO LOCAL], 
                         Area_1.Descripcion_Area AS [HIJO AREA], Area_1.Nro_Piso AS [HIJO NRO PISO], Area_1.Nro_Ambiente AS [HIJO NRO AMBIENTE], 
                         Ubigeo_1.Distrito + ' ' + Ubigeo_1.Provincia + ' ' + Ubigeo_1.Departamento AS [HIJO UBICACION], Local_1.Direccion_Local AS [HIJO DIRECCION LOCAL], 
                         dbo.TIPO_RELACION_ELEMENTO_CONFIGURACION.NOMBRE_TIPO_RELA AS [TIPO RELACION], P.NRO_SERIE AS [PADRE NRO SERIE], 
                         C.NRO_SERIE AS [HIJO NRO SERIE], dbo.MARCA.NOMBRE AS [PADRE MARCA], MARCA_1.NOMBRE AS [HIJO MARCA], 
                         dbo.MODELO.NOMBRE AS [PADRE MODELO], MODELO_1.NOMBRE AS [HIJO MODELO], 
                         P.FABRICANTE_O_PROVEEDOR AS [PADRE FABRICANTE / PROVEEDOR], C.FABRICANTE_O_PROVEEDOR AS [HIJO FABRICANTE / PROVEEDOR]
FROM            dbo.RELACION_ELEMENTO_CONFIGURACION AS R INNER JOIN
                         dbo.ELEMENTOS_CONFIGURACION AS P ON R.ELEMENTO_CONFIGURACION_PADRE = P.ID_ELEMENTO_CONFIGURACION INNER JOIN
                         dbo.ELEMENTOS_CONFIGURACION AS C ON R.ELEMENTO_CONFIGURACION_HIJO = C.ID_ELEMENTO_CONFIGURACION INNER JOIN
                         dbo.TIPO_RELACION_ELEMENTO_CONFIGURACION ON 
                         R.COD_TIPO_RELA = dbo.TIPO_RELACION_ELEMENTO_CONFIGURACION.COD_TIPO_RELA INNER JOIN
                         dbo.TIPOS_ELEMENTO_CONFIGURACION ON P.ID_TIPO = dbo.TIPOS_ELEMENTO_CONFIGURACION.ID_TIPO INNER JOIN
                         dbo.TIPOS_ELEMENTO_CONFIGURACION AS TIPOS_ELEMENTO_CONFIGURACION_1 ON 
                         C.ID_TIPO = TIPOS_ELEMENTO_CONFIGURACION_1.ID_TIPO INNER JOIN
                         dbo.ESTADO_ELEMENTO_CONFIGURACION ON P.ID_ESTADO = dbo.ESTADO_ELEMENTO_CONFIGURACION.ID_ESTADO INNER JOIN
                         dbo.ESTADO_ELEMENTO_CONFIGURACION AS ESTADO_ELEMENTO_CONFIGURACION_1 ON 
                         C.ID_ESTADO = ESTADO_ELEMENTO_CONFIGURACION_1.ID_ESTADO INNER JOIN
                         dbo.Personal ON P.PROPIETARIO = dbo.Personal.Id_Personal INNER JOIN
                         dbo.Personal AS Personal_1 ON C.PROPIETARIO = Personal_1.Id_Personal INNER JOIN
                         dbo.[DESCRIPCION_ELEMENTO CONFIGURACION] ON P.ID_DESCRIPCION = dbo.[DESCRIPCION_ELEMENTO CONFIGURACION].ID_DESCRIPCION INNER JOIN
                         dbo.[DESCRIPCION_ELEMENTO CONFIGURACION] AS [DESCRIPCION_ELEMENTO CONFIGURACION_1] ON 
                         C.ID_DESCRIPCION = [DESCRIPCION_ELEMENTO CONFIGURACION_1].ID_DESCRIPCION INNER JOIN
                         dbo.NIVEL_PRIORIDAD ON P.ID_NIVEL = dbo.NIVEL_PRIORIDAD.ID_NIVEL INNER JOIN
                         dbo.NIVEL_PRIORIDAD AS NIVEL_PRIORIDAD_1 ON C.ID_NIVEL = NIVEL_PRIORIDAD_1.ID_NIVEL INNER JOIN
                         dbo.Area ON P.LOCALIZACION_FISICA = dbo.Area.Id_Area INNER JOIN
                         dbo.Local ON dbo.Area.Id_Local = dbo.Local.Id_Local INNER JOIN
                         dbo.Sede ON dbo.Local.Id_Sede = dbo.Sede.Id_Sede INNER JOIN
                         dbo.Ubigeo ON dbo.Local.Cod_Ubi = dbo.Ubigeo.Cod_Ubi INNER JOIN
                         dbo.Area AS Area_1 ON C.LOCALIZACION_FISICA = Area_1.Id_Area INNER JOIN
                         dbo.Local AS Local_1 ON Area_1.Id_Local = Local_1.Id_Local INNER JOIN
                         dbo.Sede AS Sede_1 ON Local_1.Id_Sede = Sede_1.Id_Sede INNER JOIN
                         dbo.Ubigeo AS Ubigeo_1 ON Local_1.Cod_Ubi = Ubigeo_1.Cod_Ubi INNER JOIN
                         dbo.MARCA ON P.ID_MAR = dbo.MARCA.ID_MAR INNER JOIN
                         dbo.MARCA AS MARCA_1 ON C.ID_MAR = MARCA_1.ID_MAR INNER JOIN
                         dbo.MODELO ON P.ID_MOD = dbo.MODELO.ID_MOD INNER JOIN
                         dbo.MODELO AS MODELO_1 ON C.ID_MOD = MODELO_1.ID_MOD





GO
/****** Objeto: View [dbo].[VISTA_RELACION_ELEMENTOS_CONFIGURACION] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VISTA_RELACION_ELEMENTOS_CONFIGURACION]
AS
SELECT        R.ID_RELACION, P.ID_ELEMENTO_CONFIGURACION AS [PADRE ID], P.NOMBRE_ELEMENTO_CONFIGURACION AS [PADRE CI], 
                         dbo.TIPOS_ELEMENTO_CONFIGURACION.NOMBRE_TIPO AS [PADRE TIPO CI], 
                         dbo.ESTADO_ELEMENTO_CONFIGURACION.NOMBRE_ESTADO AS [PADRE ESTADO CI], 
                         dbo.Personal.Nombre_Personal + ' ' + dbo.Personal.ApePat_Personal + ' ' + dbo.Personal.ApeMat_Personal AS [PADRE PROPIETARIO CI], 
                         dbo.[DESCRIPCION_ELEMENTO CONFIGURACION].NOMBRE_DESCRIPCION AS [PADRE DESCRIPCION CI], 
                         dbo.NIVEL_PRIORIDAD.NOMBRE_NIVEL AS [PADRE NIVEL PRIORIDAD], dbo.Sede.Descripcion_Sede AS [PADRE SEDE], 
                         dbo.Local.Nombre_Local AS [PADRE LOCAL], dbo.Area.Descripcion_Area AS [PADRE AREA], dbo.Area.Nro_Piso AS [PADRE NRO PISO], 
                         dbo.Area.Nro_Ambiente AS [PADRE NRO AMBIENTE], dbo.Ubigeo.Distrito + ' ' + dbo.Ubigeo.Provincia + ' ' + dbo.Ubigeo.Departamento AS [PADRE UBICACION],
                          dbo.Local.Direccion_Local AS [PADRE DIRECCION LOCAL], C.ID_ELEMENTO_CONFIGURACION AS [HIJO ID], 
                         C.NOMBRE_ELEMENTO_CONFIGURACION AS [HIJO CI], TIPOS_ELEMENTO_CONFIGURACION_1.NOMBRE_TIPO AS [HIJO TIPO CI], 
                         ESTADO_ELEMENTO_CONFIGURACION_1.NOMBRE_ESTADO AS [HIJO ESTADO CI], 
                         Personal_1.Nombre_Personal + ' ' + Personal_1.ApePat_Personal + ' ' + Personal_1.ApeMat_Personal AS [HIJO PROPIETARIO CI], 
                         [DESCRIPCION_ELEMENTO CONFIGURACION_1].NOMBRE_DESCRIPCION AS [HIJO DESCRIPCION CI], 
                         NIVEL_PRIORIDAD_1.NOMBRE_NIVEL AS [HIJO NIVEL PRIORIDAD], Sede_1.Descripcion_Sede AS [HIJO SEDE], Local_1.Nombre_Local AS [HIJO LOCAL], 
                         Area_1.Descripcion_Area AS [HIJO AREA], Area_1.Nro_Piso AS [HIJO NRO PISO], Area_1.Nro_Ambiente AS [HIJO NRO AMBIENTE], 
                         Ubigeo_1.Distrito + ' ' + Ubigeo_1.Provincia + ' ' + Ubigeo_1.Departamento AS [HIJO UBICACION], Local_1.Direccion_Local AS [HIJO DIRECCION LOCAL], 
                         dbo.TIPO_RELACION_ELEMENTO_CONFIGURACION.NOMBRE_TIPO_RELA AS [TIPO RELACION], P.NRO_SERIE AS [PADRE NRO SERIE], 
                         C.NRO_SERIE AS [HIJO NRO SERIE], P.FABRICANTE_O_PROVEEDOR AS [PADRE FABICANTE / PROVEEDOR], 
                         C.FABRICANTE_O_PROVEEDOR AS [HIJO FABRICANTE / PROVEEDOR], P.IP AS [PADRE IP], P.GATEWAY AS [PADRE GATEWAY], C.IP AS [HIJO IP], 
                         C.GATEWAY AS [HIJO GATEWAY], P.GRUPO_TRABAJO AS [PADRE GRUPO TRABAJO], C.GRUPO_TRABAJO AS [HIJO GRUPO TRABAJO]
FROM            dbo.RELACION_ELEMENTO_CONFIGURACION AS R INNER JOIN
                         dbo.ELEMENTOS_CONFIGURACION AS P ON R.ELEMENTO_CONFIGURACION_PADRE = P.ID_ELEMENTO_CONFIGURACION INNER JOIN
                         dbo.ELEMENTOS_CONFIGURACION AS C ON R.ELEMENTO_CONFIGURACION_HIJO = C.ID_ELEMENTO_CONFIGURACION INNER JOIN
                         dbo.TIPO_RELACION_ELEMENTO_CONFIGURACION ON 
                         R.COD_TIPO_RELA = dbo.TIPO_RELACION_ELEMENTO_CONFIGURACION.COD_TIPO_RELA INNER JOIN
                         dbo.TIPOS_ELEMENTO_CONFIGURACION ON P.ID_TIPO = dbo.TIPOS_ELEMENTO_CONFIGURACION.ID_TIPO INNER JOIN
                         dbo.TIPOS_ELEMENTO_CONFIGURACION AS TIPOS_ELEMENTO_CONFIGURACION_1 ON 
                         C.ID_TIPO = TIPOS_ELEMENTO_CONFIGURACION_1.ID_TIPO INNER JOIN
                         dbo.ESTADO_ELEMENTO_CONFIGURACION ON P.ID_ESTADO = dbo.ESTADO_ELEMENTO_CONFIGURACION.ID_ESTADO INNER JOIN
                         dbo.ESTADO_ELEMENTO_CONFIGURACION AS ESTADO_ELEMENTO_CONFIGURACION_1 ON 
                         C.ID_ESTADO = ESTADO_ELEMENTO_CONFIGURACION_1.ID_ESTADO INNER JOIN
                         dbo.Personal ON P.PROPIETARIO = dbo.Personal.Id_Personal INNER JOIN
                         dbo.Personal AS Personal_1 ON C.PROPIETARIO = Personal_1.Id_Personal INNER JOIN
                         dbo.[DESCRIPCION_ELEMENTO CONFIGURACION] ON P.ID_DESCRIPCION = dbo.[DESCRIPCION_ELEMENTO CONFIGURACION].ID_DESCRIPCION INNER JOIN
                         dbo.[DESCRIPCION_ELEMENTO CONFIGURACION] AS [DESCRIPCION_ELEMENTO CONFIGURACION_1] ON 
                         C.ID_DESCRIPCION = [DESCRIPCION_ELEMENTO CONFIGURACION_1].ID_DESCRIPCION INNER JOIN
                         dbo.NIVEL_PRIORIDAD ON P.ID_NIVEL = dbo.NIVEL_PRIORIDAD.ID_NIVEL INNER JOIN
                         dbo.NIVEL_PRIORIDAD AS NIVEL_PRIORIDAD_1 ON C.ID_NIVEL = NIVEL_PRIORIDAD_1.ID_NIVEL INNER JOIN
                         dbo.Area ON P.LOCALIZACION_FISICA = dbo.Area.Id_Area INNER JOIN
                         dbo.Local ON dbo.Area.Id_Local = dbo.Local.Id_Local INNER JOIN
                         dbo.Sede ON dbo.Local.Id_Sede = dbo.Sede.Id_Sede INNER JOIN
                         dbo.Ubigeo ON dbo.Local.Cod_Ubi = dbo.Ubigeo.Cod_Ubi INNER JOIN
                         dbo.Area AS Area_1 ON C.LOCALIZACION_FISICA = Area_1.Id_Area INNER JOIN
                         dbo.Local AS Local_1 ON Area_1.Id_Local = Local_1.Id_Local INNER JOIN
                         dbo.Sede AS Sede_1 ON Local_1.Id_Sede = Sede_1.Id_Sede INNER JOIN
                         dbo.Ubigeo AS Ubigeo_1 ON Local_1.Cod_Ubi = Ubigeo_1.Cod_Ubi





GO
/****** Objeto: View [dbo].[VISTA_REPORTE_ELEMENTOS_CONFIGURACION] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VISTA_REPORTE_ELEMENTOS_CONFIGURACION]
AS
SELECT        dbo.ELEMENTOS_CONFIGURACION.ID_ELEMENTO_CONFIGURACION AS [ID CI], dbo.ELEMENTOS_CONFIGURACION.NOMBRE_ELEMENTO_CONFIGURACION AS [NOMBRE CI], 
                         dbo.TIPOS_ELEMENTO_CONFIGURACION.NOMBRE_TIPO AS [NOMBRE TIPO CI], dbo.ESTADO_ELEMENTO_CONFIGURACION.NOMBRE_ESTADO AS [ESTADO CI], 
                         dbo.Personal.Nombre_Personal + ' ' + dbo.Personal.ApePat_Personal + ' ' + dbo.Personal.ApeMat_Personal AS PROPIETARIO, dbo.[DESCRIPCION_ELEMENTO CONFIGURACION].NOMBRE_DESCRIPCION AS [DESCRIPCION CI], 
                         dbo.IMPACTO_COMERCIAL_ELE_CONF_HAR.NOMBRE AS [IMPACTO CI], dbo.Sede.Descripcion_Sede AS SEDE, dbo.Local.Nombre_Local AS LOCAL, 
                         dbo.Ubigeo.Distrito + '/ ' + dbo.Ubigeo.Provincia + ' /' + dbo.Ubigeo.Departamento AS [UBICACION LOCAL], dbo.Local.Direccion_Local AS [DIRECCION LOCAL], dbo.Area.Descripcion_Area AS AREA, 
                         dbo.Area.Nro_Piso AS [NRO PISO], dbo.Area.Nro_Ambiente AS [NRO AMBIENTE], dbo.ELEMENTOS_CONFIGURACION.FECHA_REGISTRO AS [FEC. CREACION CI], 
                         dbo.Usuario.Nombre + ' ' + dbo.Usuario.ApePat + ' ' + dbo.Usuario.ApeMat AS RESPONSABLE, dbo.NIVEL_PRIORIDAD.NOMBRE_NIVEL AS [NIVEL PRIORIDAD], dbo.ELEMENTOS_CONFIGURACION.NRO_SERIE AS [NRO SERIE], 
                         dbo.ELEMENTOS_CONFIGURACION.FABRICANTE_O_PROVEEDOR AS [FABRICANTE / PROVEEDOR], dbo.MARCA.NOMBRE AS MARCA, dbo.MODELO.NOMBRE AS MODELO, dbo.ELEMENTOS_CONFIGURACION.IP, 
                         dbo.ELEMENTOS_CONFIGURACION.GATEWAY, dbo.ELEMENTOS_CONFIGURACION.GRUPO_TRABAJO AS [GRUPO TRABAJO]
FROM            dbo.ELEMENTOS_CONFIGURACION INNER JOIN
                         dbo.TIPOS_ELEMENTO_CONFIGURACION ON dbo.ELEMENTOS_CONFIGURACION.ID_TIPO = dbo.TIPOS_ELEMENTO_CONFIGURACION.ID_TIPO INNER JOIN
                         dbo.ESTADO_ELEMENTO_CONFIGURACION ON dbo.ELEMENTOS_CONFIGURACION.ID_ESTADO = dbo.ESTADO_ELEMENTO_CONFIGURACION.ID_ESTADO INNER JOIN
                         dbo.Personal ON dbo.ELEMENTOS_CONFIGURACION.PROPIETARIO = dbo.Personal.Id_Personal INNER JOIN
                         dbo.[DESCRIPCION_ELEMENTO CONFIGURACION] ON dbo.ELEMENTOS_CONFIGURACION.ID_DESCRIPCION = dbo.[DESCRIPCION_ELEMENTO CONFIGURACION].ID_DESCRIPCION INNER JOIN
                         dbo.IMPACTO_COMERCIAL_ELE_CONF_HAR ON dbo.ELEMENTOS_CONFIGURACION.ID_IMP_ELE_CONF_HAR = dbo.IMPACTO_COMERCIAL_ELE_CONF_HAR.ID_IMP_ELE_CONF_HAR INNER JOIN
                         dbo.Area ON dbo.ELEMENTOS_CONFIGURACION.LOCALIZACION_FISICA = dbo.Area.Id_Area INNER JOIN
                         dbo.Local ON dbo.Area.Id_Local = dbo.Local.Id_Local INNER JOIN
                         dbo.Sede ON dbo.Local.Id_Sede = dbo.Sede.Id_Sede INNER JOIN
                         dbo.Ubigeo ON dbo.Local.Cod_Ubi = dbo.Ubigeo.Cod_Ubi INNER JOIN
                         dbo.Usuario ON dbo.ELEMENTOS_CONFIGURACION.RESPONSABLE_REGISTRO = dbo.Usuario.Id_Uusario INNER JOIN
                         dbo.NIVEL_PRIORIDAD ON dbo.ELEMENTOS_CONFIGURACION.ID_NIVEL = dbo.NIVEL_PRIORIDAD.ID_NIVEL INNER JOIN
                         dbo.MARCA ON dbo.ELEMENTOS_CONFIGURACION.ID_MAR = dbo.MARCA.ID_MAR INNER JOIN
                         dbo.MODELO ON dbo.ELEMENTOS_CONFIGURACION.ID_MOD = dbo.MODELO.ID_MOD




GO
/****** Objeto: View [dbo].[VISTA_UBIGEO] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VISTA_UBIGEO]
AS
SELECT        Cod_Ubi AS ID, Codigo AS CODIGO, Departamento AS DEPARTAMENTO, Provincia AS PROVINCIA, Distrito AS DISTRITO
FROM            dbo.Ubigeo





GO
/****** Objeto: Table [dbo].[autorizacion] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[autorizacion](
	[id_autorizacion] [int] IDENTITY(1,1) NOT NULL,
	[id_formulario] [int] NOT NULL,
	[IDPer] [int] NOT NULL,
	[aprobacion_autorizacion] [bit] NOT NULL,
 CONSTRAINT [PK_autorizacion] PRIMARY KEY CLUSTERED 
(
	[id_autorizacion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[derecho] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[derecho](
	[id_derecho] [int] IDENTITY(1,1) NOT NULL,
	[nombre_derecho] [varchar](max) NOT NULL,
 CONSTRAINT [PK_derecho] PRIMARY KEY CLUSTERED 
(
	[id_derecho] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[DETALLE_ESTADO_ACTUAL_ELEMENTO_CONFIGURACION] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DETALLE_ESTADO_ACTUAL_ELEMENTO_CONFIGURACION](
	[ID_DET_EST_ACT_CI] [int] IDENTITY(1,1) NOT NULL,
	[ID_SEGUIMIENTO] [int] NOT NULL,
	[ID_ESTADO_ACTUAL] [int] NOT NULL,
 CONSTRAINT [PK_DETALLE_ESTADO_ACTUAL_ELEMENTO_CONFIGURACION] PRIMARY KEY CLUSTERED 
(
	[ID_DET_EST_ACT_CI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[ESTADO_ACTUAL_ELEMENTO_CONFIGURACION] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ESTADO_ACTUAL_ELEMENTO_CONFIGURACION](
	[ID_ESTADO_ACTUAL] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE_ESTADO_ACTUL] [varchar](max) NOT NULL,
 CONSTRAINT [PK_ESTADO_ACTUAL_ELEMENTO_CONFIGURACION] PRIMARY KEY CLUSTERED 
(
	[ID_ESTADO_ACTUAL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[formulario] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[formulario](
	[id_formulario] [int] IDENTITY(1,1) NOT NULL,
	[nombre_formulario] [varchar](max) NOT NULL,
 CONSTRAINT [PK_formulario] PRIMARY KEY CLUSTERED 
(
	[id_formulario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[permiso] Fecha de script: 18/05/2026 10:08:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[permiso](
	[id_permiso] [int] IDENTITY(1,1) NOT NULL,
	[id_autorizacion] [int] NOT NULL,
	[id_derecho] [int] NOT NULL,
	[aprobacion_permiso] [bit] NOT NULL,
 CONSTRAINT [PK_permiso] PRIMARY KEY CLUSTERED 
(
	[id_permiso] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
