USE [master]
GO
/****** Objeto: Database [GCS] Fecha de script: 18/05/2026 10:08:30 ******/
CREATE DATABASE [GCS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GCS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\GCS.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GCS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\GCS_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [GCS] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GCS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [GCS] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [GCS] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [GCS] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [GCS] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [GCS] SET ARITHABORT OFF 
GO
ALTER DATABASE [GCS] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [GCS] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [GCS] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [GCS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [GCS] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [GCS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [GCS] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [GCS] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [GCS] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [GCS] SET  DISABLE_BROKER 
GO
ALTER DATABASE [GCS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [GCS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [GCS] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [GCS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [GCS] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [GCS] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [GCS] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [GCS] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [GCS] SET  MULTI_USER 
GO
ALTER DATABASE [GCS] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [GCS] SET DB_CHAINING OFF 
GO
ALTER DATABASE [GCS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [GCS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [GCS] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [GCS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [GCS] SET QUERY_STORE = ON
GO
ALTER DATABASE [GCS] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [GCS]
GO
/****** Objeto: User [sistema] Fecha de script: 18/05/2026 10:08:30 ******/
CREATE USER [sistema] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [sistema]
GO
/****** Objeto: UserDefinedFunction [dbo].[_Cantidad_CIs_CMDB] Fecha de script: 18/05/2026 10:08:30 ******/
