USE [GCS]
GO

-- ============================================================
-- SEP1: SCHEMA Y TABLAS
-- Generated: 2026-05-18
-- ============================================================

-- Sede
CREATE TABLE [dbo].[Sede](
	[Id_Sede] [int] IDENTITY(1,1) NOT NULL,
	[CodIgo_Sede] [varchar](2) NOT NULL,
	[Descripcion_Sede] [varchar](30) NOT NULL,
 CONSTRAINT [PK_Sede] PRIMARY KEY CLUSTERED
([Id_Sede] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

-- Local
CREATE TABLE [dbo].[Local](
	[Id_Local] [int] IDENTITY(1,1) NOT NULL,
	[Codigo_Local] [varchar](6) NOT NULL,
	[Nombre_Local] [varchar](max) NOT NULL,
	[Direccion_Local] [varchar](max) NULL,
	[Id_Sede] [int] NOT NULL,
	[Telefono_local] [varchar](9) NULL,
	[Cod_Ubi] [varchar](9) NULL,
 CONSTRAINT [PK_Local] PRIMARY KEY CLUSTERED
([Id_Local] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

-- Area
CREATE TABLE [dbo].[Area](
	[Id_Area] [int] IDENTITY(1,1) NOT NULL,
	[Codigo_Area] [varchar](6) NOT NULL,
	[Descripcion_Area] [varchar](max) NOT NULL,
	[Nro_Piso] [char](1) NOT NULL,
	[Nro_Ambiente] [varchar](3) NOT NULL,
	[Id_Local] [int] NOT NULL,
 CONSTRAINT [PK_Area_1] PRIMARY KEY CLUSTERED
([Id_Area] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

-- Dependencia
CREATE TABLE [dbo].[Dependencia](
	[Id_Dependencia] [int] IDENTITY(1,1) NOT NULL,
	[Codigo_Depemdencia] [varchar](4) NOT NULL,
	[Nombre_Dependencia] [varchar](max) NOT NULL,
 CONSTRAINT [PK_Dependencia] PRIMARY KEY CLUSTERED
([Id_Dependencia] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

-- Profesion_Ocupacion
CREATE TABLE [dbo].[Profesion_Ocupacion](
	[Id_prof_ocup] [int] IDENTITY(1,1) NOT NULL,
	[Prof_Ocup] [varchar](250) NOT NULL,
	[Descripcion_prof_ocup] [varchar](250) NULL,
 CONSTRAINT [PK_Profes_Ocupac] PRIMARY KEY CLUSTERED
([Id_prof_ocup] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

-- Tipo_de_Documento_de_Identidad
CREATE TABLE [dbo].[Tipo_de_Documento_de_Identidad](
	[Id_Tipo_Documento] [int] IDENTITY(1,1) NOT NULL,
	[Codigo_Tipo_Documento] [varchar](1) NOT NULL,
	[Nombre_Tipo_Documento] [varchar](50) NOT NULL,
	[Siglas_Tipo_Documento] [varchar](5) NOT NULL,
	[Descrip_Tipo_Documento] [varchar](100) NULL,
 CONSTRAINT [PK_Tipo_de_Documento_de_Identidad] PRIMARY KEY CLUSTERED
([Id_Tipo_Documento] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

-- CARGO
CREATE TABLE [dbo].[CARGO](
	[Id_Cargo] [int] IDENTITY(1,1) NOT NULL,
	[Nombre_Cargo] [varchar](max) NOT NULL,
 CONSTRAINT [PK_CARGO] PRIMARY KEY CLUSTERED
([Id_Cargo] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

-- Personal
CREATE TABLE [dbo].[Personal](
	[Id_Personal] [int] IDENTITY(1,1) NOT NULL,
	[Codigo_Personal] [varchar](5) NOT NULL,
	[Nombre_Personal] [varchar](25) NOT NULL,
	[ApePat_Personal] [varchar](25) NOT NULL,
	[ApeMat_Personal] [varchar](25) NOT NULL,
	[Id_Tipo_Documento] [int] NOT NULL,
	[Nro_Dni_Personal] [varchar](max) NOT NULL,
	[Id_prof_ocup] [int] NOT NULL,
	[Tel_Personal] [varchar](9) NULL,
	[Email_Personal] [varchar](max) NULL,
	[Id_Area] [int] NOT NULL,
	[Id_Dependencia] [int] NOT NULL,
	[Estado_Personal] [bit] NOT NULL,
	[ID_CARGO] [int] NULL,
 CONSTRAINT [PK_Personal] PRIMARY KEY CLUSTERED
([Id_Personal] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

-- Ubigeo
CREATE TABLE [dbo].[Ubigeo](
	[Cod_Ubi] [varchar](9) NOT NULL,
	[Distrito] [varchar](100) NULL,
	[Provincia] [varchar](100) NULL,
	[Departamento] [varchar](100) NULL,
 CONSTRAINT [PK_Ubigeo] PRIMARY KEY CLUSTERED
([Cod_Ubi] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

-- MARCA
CREATE TABLE [dbo].[MARCA](
	[ID_MAR] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](max) NOT NULL,
 CONSTRAINT [PK_MARCA] PRIMARY KEY CLUSTERED
([ID_MAR] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

-- MODELO
CREATE TABLE [dbo].[MODELO](
	[ID_MOD] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](max) NOT NULL,
 CONSTRAINT [PK_MODELO] PRIMARY KEY CLUSTERED
([ID_MOD] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

-- TIPOS_ELEMENTO_CONFIGURACION
CREATE TABLE [dbo].[TIPOS_ELEMENTO_CONFIGURACION](
	[ID_TIPO] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE_TIPO] [varchar](max) NOT NULL,
 CONSTRAINT [PK_TIPOS_ELEMENTO_CONFIGURACION] PRIMARY KEY CLUSTERED
([ID_TIPO] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

-- ESTADO_ELEMENTO_CONFIGURACION
CREATE TABLE [dbo].[ESTADO_ELEMENTO_CONFIGURACION](
	[ID_ESTADO] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE_ESTADO] [varchar](15) NOT NULL,
 CONSTRAINT [PK_ESTADO_ELEMENTO_CONFIGURACION] PRIMARY KEY CLUSTERED
([ID_ESTADO] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

-- NIVEL_PRIORIDAD
CREATE TABLE [dbo].[NIVEL_PRIORIDAD](
	[ID_NIVEL] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE_NIVEL] [varchar](10) NOT NULL,
 CONSTRAINT [PK_NIVEL_PRIORIDAD] PRIMARY KEY CLUSTERED
([ID_NIVEL] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

-- IMPACTO_COMERCIAL_ELE_CONF_HAR
CREATE TABLE [dbo].[IMPACTO_COMERCIAL_ELE_CONF_HAR](
	[ID_IMP_ELE_CONF_HAR] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](10) NOT NULL,
 CONSTRAINT [PK_IMPACTO_COMERCIAL_ELE_CONF_HAR] PRIMARY KEY CLUSTERED
([ID_IMP_ELE_CONF_HAR] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

-- ELEMENTOS_CONFIGURACION
CREATE TABLE [dbo].[ELEMENTOS_CONFIGURACION](
	[ID_ELEMENTO_CONFIGURACION] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE_ELEMENTO_CONFIGURACION] [varchar](max) NULL,
	[ID_TIPO] [int] NULL,
	[ID_ESTADO] [int] NULL,
	[PROPIETARIO] [int] NULL,
	[ID_DESCRIPCION] [int] NULL,
	[ID_IMP_ELE_CONF_HAR] [int] NULL,
	[LOCALIZACION_FISICA] [int] NULL,
	[FECHA_REGISTRO] [datetime] NULL,
	[RESPONSABLE_REGISTRO] [int] NULL,
	[ID_NIVEL] [int] NULL,
	[NRO_SERIE] [varchar](max) NULL,
	[FABRICANTE_O_PROVEEDOR] [varchar](max) NULL,
	[ID_MAR] [int] NULL,
	[ID_MOD] [int] NULL,
	[IP] [varchar](15) NULL,
	[GATEWAY] [varchar](15) NULL,
	[GRUPO_TRABAJO] [varchar](max) NULL,
 CONSTRAINT [PK_ELE_CONF_HAR_1] PRIMARY KEY CLUSTERED
([ID_ELEMENTO_CONFIGURACION] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

PRINT 'SEP1: Tablas creadas correctamente'
GO