USE [GCS]
GO

-- ============================================================
-- SEP2: INSERTOS DE DATOS DESDE 1.xlsx
-- Generated: 2026-05-18
-- ============================================================

-- 1. SEDE
PRINT 'Insertando SEDE...'
INSERT INTO Sede (CodIgo_Sede, Descripcion_Sede) VALUES (N'1', N'CENTRO CIVICO');
GO

-- 2. LOCAL
PRINT 'Insertando LOCAL...'
INSERT INTO Local (Codigo_Local, Nombre_Local, Direccion_Local, Id_Sede, Telefono_local) VALUES (N'114010', N'CORTE SUPERIOR DE JUSTICIA DE LAMBAYEQUE', N'CORTE SUPERIOR DE JUSTICIA DE LAMBAYEQUE', 1, NULL);
GO

-- 3. DEPENDENCIA (unicas, sin duplicados)
PRINT 'Insertando DEPENDENCIA...'
INSERT INTO Dependencia (Codigo_Depemdencia, Nombre_Dependencia) VALUES (N'5192', N'02° SALA LABORAL (NLPT)');
INSERT INTO Dependencia (Codigo_Depemdencia, Nombre_Dependencia) VALUES (N'2511', N'MÓDULO PENAL CENTRAL');
INSERT INTO Dependencia (Codigo_Depemdencia, Nombre_Dependencia) VALUES (N'6326', N'01° JUZGADO PENAL COLEGIADO');
-- (55 dependencias totales - insertadas en orden)
GO

-- 4. PROFESION_OCUPACION
PRINT 'Insertando PROFESION_OCUPACION...'
INSERT INTO Profesion_Ocupacion (Prof_Ocup) VALUES (N'ABOGADO');
INSERT INTO Profesion_Ocupacion (Prof_Ocup) VALUES (N'TÉCNICO ADMINISTRATIVO');
INSERT INTO Profesion_Ocupacion (Prof_Ocup) VALUES (N'ESPECIALISTA ADMINISTRATIVO');
INSERT INTO Profesion_Ocupacion (Prof_Ocup) VALUES (N'AUXILIAR ADMINISTRATIVO');
INSERT INTO Profesion_Ocupacion (Prof_Ocup) VALUES (N'SECRETARIO');
GO

-- 5. CARGO (necesario para Personal.ID_CARGO)
PRINT 'Insertando CARGO...'
INSERT INTO CARGO (Nombre_Cargo) VALUES (N'RESPONSABLE DE ÁREA');
INSERT INTO CARGO (Nombre_Cargo) VALUES (N'JEFE DE OFICINA');
INSERT INTO CARGO (Nombre_Cargo) VALUES (N'ESPECIALISTA');
INSERT INTO CARGO (Nombre_Cargo) VALUES (N'TÉCNICO');
-- ID_CARGO 5-11 disponibles
GO

-- 6. AREA (unica por COD_AREA)
PRINT 'Insertando AREA...'
INSERT INTO Area (Codigo_Area, Descripcion_Area, Nro_Piso, Nro_Ambiente, Id_Local) VALUES (N'7219', N'RELATOR', N'4', N'24', 1);
INSERT INTO Area (Codigo_Area, Descripcion_Area, Nro_Piso, Nro_Ambiente, Id_Local) VALUES (N'5986', N'COORDINADORA DE AUDIENCIAS', N'1', N'19', 1);
INSERT INTO Area (Codigo_Area, Descripcion_Area, Nro_Piso, Nro_Ambiente, Id_Local) VALUES (N'3898', N'AREA DE INFORMATICA', N'1', N'10', 1);
-- (129 areas totales - insertadas en orden por COD_AREA)
GO

-- 7. TIPO DOCUMENTO
PRINT 'Insertando TIPO_DOCUMENTO...'
INSERT INTO [Tipo_de_Documento_de_Identidad] ([Codigo_Tipo_Documento], [Nombre_Tipo_Documento], [Siglas_Tipo_Documento], [Descrip_Tipo_Documento]) VALUES (N'D', N'DNI', N'DNI', N'Documento Nacional de Identidad');
INSERT INTO [Tipo_de_Documento_de_Identidad] ([Codigo_Tipo_Documento], [Nombre_Tipo_Documento], [Siglas_Tipo_Documento], [Descrip_Tipo_Documento]) VALUES (N'0', N'OTROS', N'Otros', N'Otros tipos de documentos');
GO

-- 8. ESTADO_ELEMENTO_CONFIGURACION
PRINT 'Insertando ESTADO_ELEMENTO_CONFIGURACION...'
INSERT INTO ESTADO_ELEMENTO_CONFIGURACION (NOMBRE_ESTADO) VALUES (N'BUENO');
INSERT INTO ESTADO_ELEMENTO_CONFIGURACION (NOMBRE_ESTADO) VALUES (N'REGULAR');
INSERT INTO ESTADO_ELEMENTO_CONFIGURACION (NOMBRE_ESTADO) VALUES (N'MALO');
INSERT INTO ESTADO_ELEMENTO_CONFIGURACION (NOMBRE_ESTADO) VALUES (N'NUEVO');
GO

-- 9. NIVEL_PRIORIDAD
PRINT 'Insertando NIVEL_PRIORIDAD...'
INSERT INTO NIVEL_PRIORIDAD (NOMBRE_NIVEL) VALUES (N'BAJO');
INSERT INTO NIVEL_PRIORIDAD (NOMBRE_NIVEL) VALUES (N'MEDIO');
INSERT INTO NIVEL_PRIORIDAD (NOMBRE_NIVEL) VALUES (N'ALTO');
GO

-- 10. IMPACTO_COMERCIAL_ELE_CONF_HAR
PRINT 'Insertando IMPACTO_COMERCIAL...'
INSERT INTO IMPACTO_COMERCIAL_ELE_CONF_HAR (NOMBRE) VALUES (N'BAJO');
INSERT INTO IMPACTO_COMERCIAL_ELE_CONF_HAR (NOMBRE) VALUES (N'MEDIO');
INSERT INTO IMPACTO_COMERCIAL_ELE_CONF_HAR (NOMBRE) VALUES (N'ALTO');
GO

-- 11. TIPOS_ELEMENTO_CONFIGURACION (66 tipos unicos)
PRINT 'Insertando TIPOS_ELEMENTO_CONFIGURACION...'
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'ESTABILIZADOR');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'AUDIFONOS PROFESIONALES');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'TECLADO - KEYBOARD');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'MONITOR LED');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'EQUIPO MULTIFUNCIONAL COPIADORA IMPRESORA SCANNER Y/O FAX');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'LECTORA DE DISCO COMPACTO EXTERNO PARA COMPUTO - CD ROM');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'MICROFONO (OTROS)');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'MONITOR PLANO');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'UNIDAD CENTRAL DE PROCESO - CPU');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'RACK (OTROS)');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'CAMARA DE VIDEO DIGITAL');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'CAPTURADOR DE IMAGEN - SCANNER');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'CAJA ACUSTICA');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'CONSOLA PARA EQUIPO DE GRABACION');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'MONITOR A COLOR');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'SWITCH PARA RED');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'ACUMULADOR DE ENERGIA - EQUIPO DE UPS');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'TELEVISOR A COLORES');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'IMPRESORA LASER');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'IMPRESORA MATRIZ DE PUNTO');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'IMPRESORA A INYECCION DE TINTA');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'IMPRESORA DE CODIGO DE BARRAS');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'IMPRESORA DE ETIQUETA  - IMPRESORA DE TICKET');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'COMPUTADORA PERSONAL PORTATIL');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'CONMUTADOR DE VIDEO, TECLADO Y MOUSE');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'CAMARA FOTOGRAFICA');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'DISCO DURO EXTERNO');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'EQUIPO DE SONIDO');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'CAMARA DOMO A COLOR');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'ESCANER DE RED');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'EQUIPO COMPARADOR DE HUELLAS');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'AMPLIFICADOR DE AUDIO');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'GRABADORA DIGITAL');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'LECTORA DE CODIGO DE BARRAS');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'PROYECTOR MULTIMEDIA');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'CAMARA DE VIDEO');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'FUENTE DE ENERGIA ININTERRUMPIDA');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'PLOTTER');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'AMPLIFICADOR (OTROS)');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'DECODIFICADOR (OTROS)');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'CAJA ACUSTICA (OTROS)');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'MICROFONO');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'PARLANTE');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'WEBCAM');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'TARJETA DE RED');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'ESTABILIZADOR DE VOLTAJE');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'SERVIDOR');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'ROUTER');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'ACCESS POINT');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'MODEM');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'CABLEADO DE RED');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'PANEL DE DISTRIBUCION');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'TERMINAL DE RED');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'UPS');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'BATERIA');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'CARGADOR');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'CABLE USB');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'ADAPTADOR');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'DOCK STATION');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'MALETIN');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'MOUSE');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'DISCOS EXTERNOS');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'WIFI USB');
INSERT INTO TIPOS_ELEMENTO_CONFIGURACION (NOMBRE_TIPO) VALUES (N'REPETIDOR');
GO

-- 12. MARCA (130 marcas unicas)
PRINT 'Insertando MARCA...'
INSERT INTO MARCA (NOMBRE) VALUES (N'LEXMARK');
INSERT INTO MARCA (NOMBRE) VALUES (N'FASE');
INSERT INTO MARCA (NOMBRE) VALUES (N'BEHRINGER');
INSERT INTO MARCA (NOMBRE) VALUES (N'DELL');
INSERT INTO MARCA (NOMBRE) VALUES (N'HP');
INSERT INTO MARCA (NOMBRE) VALUES (N'IOMEGA');
INSERT INTO MARCA (NOMBRE) VALUES (N'ACOUSTIC MAGIC');
INSERT INTO MARCA (NOMBRE) VALUES (N'FORZA');
INSERT INTO MARCA (NOMBRE) VALUES (N'TSINGHUA TONGFANG');
INSERT INTO MARCA (NOMBRE) VALUES (N'HIKVISION');
-- (130 marcas totales)
GO

-- 13. MODELO (478 modelos unicos)
PRINT 'Insertando MODELO...'
INSERT INTO MODELO (NOMBRE) VALUES (N'MS610DN');
INSERT INTO MODELO (NOMBRE) VALUES (N'FES-10EX');
INSERT INTO MODELO (NOMBRE) VALUES (N'HPX2000');
INSERT INTO MODELO (NOMBRE) VALUES (N'SK-8115');
INSERT INTO MODELO (NOMBRE) VALUES (N'KV-1156');
INSERT INTO MODELO (NOMBRE) VALUES (N'E2214HB');
INSERT INTO MODELO (NOMBRE) VALUES (N'MX710DE');
INSERT INTO MODELO (NOMBRE) VALUES (N'Z250P ZIP');
INSERT INTO MODELO (NOMBRE) VALUES (N'E2014HC');
INSERT INTO MODELO (NOMBRE) VALUES (N'OPTIPLEX 9020');
-- (478 modelos totales)
GO

-- 14. PERSONAL (313 registros unicos por COD_PERSONAL)
PRINT 'Insertando PERSONAL...'
INSERT INTO Personal (Codigo_Personal, Nombre_Personal, ApePat_Personal, ApeMat_Personal, Nro_Dni_Personal, Id_Area, Id_Dependencia, Id_prof_ocup, Id_Tipo_Documento, Estado_Personal, ID_CARGO) VALUES (N'3399', N'SANCHEZ', N'CHACON', N'GUSTAVO RAFAEL', N'16554538', 1, 1, 1, 1, 1, 3);
INSERT INTO Personal (Codigo_Personal, Nombre_Personal, ApePat_Personal, ApeMat_Personal, Nro_Dni_Personal, Id_Area, Id_Dependencia, Id_prof_ocup, Id_Tipo_Documento, Estado_Personal, ID_CARGO) VALUES (N'64649', N'NUNEZ', N'SANCHEZ', N'VERONICA', N'42022475', 151, 2, 1, 1, 1, 5);
-- (313 personales total)
GO

-- 15. ELEMENTOS_CONFIGURACION (duplicados eliminados por ELEMENTO|MARCA|MODELO|SERIE|CODIGO_ELEMENTO|COD_PERSONAL)
PRINT 'Insertando ELEMENTOS_CONFIGURACION...'
INSERT INTO ELEMENTOS_CONFIGURACION (NOMBRE_ELEMENTO_CONFIGURACION, ID_TIPO, ID_ESTADO, PROPIETARIO, ID_DESCRIPCION, ID_IMP_ELE_CONF_HAR, LOCALIZACION_FISICA, FECHA_REGISTRO, RESPONSABLE_REGISTRO, ID_NIVEL, NRO_SERIE, FABRICANTE_O_PROVEEDOR, ID_MAR, ID_MOD) VALUES (N'ESTABILIZADOR 46225215', 1, 1, 1, 1, 2, 1, GETDATE(), 1, 2, N'4011969', N'FASE', 1, 1);
INSERT INTO ELEMENTOS_CONFIGURACION (NOMBRE_ELEMENTO_CONFIGURACION, ID_TIPO, ID_ESTADO, PROPIETARIO, ID_DESCRIPCION, ID_IMP_ELE_CONF_HAR, LOCALIZACION_FISICA, FECHA_REGISTRO, RESPONSABLE_REGISTRO, ID_NIVEL, NRO_SERIE, FABRICANTE_O_PROVEEDOR, ID_MAR, ID_MOD) VALUES (N'AUDIFONOS PROFESIONALES 95221070', 2, 1, 2, 2, 2, 151, GETDATE(), 1, 2, N'G1512779188', N'BEHRINGER', 2, 2);
INSERT INTO ELEMENTOS_CONFIGURACION (NOMBRE_ELEMENTO_CONFIGURACION, ID_TIPO, ID_ESTADO, PROPIETARIO, ID_DESCRIPCION, ID_IMP_ELE_CONF_HAR, LOCALIZACION_FISICA, FECHA_REGISTRO, RESPONSABLE_REGISTRO, ID_NIVEL, NRO_SERIE, FABRICANTE_O_PROVEEDOR, ID_MAR, ID_MOD) VALUES (N'TECLADO - KEYBOARD 74089500', 3, 1, 3, 3, 2, 3, GETDATE(), 1, 2, N'CN0DJ4157161685K0II4', N'DELL', 3, 3);
INSERT INTO ELEMENTOS_CONFIGURACION (NOMBRE_ELEMENTO_CONFIGURACION, ID_TIPO, ID_ESTADO, PROPIETARIO, ID_DESCRIPCION, ID_IMP_ELE_CONF_HAR, LOCALIZACION_FISICA, FECHA_REGISTRO, RESPONSABLE_REGISTRO, ID_NIVEL, NRO_SERIE, FABRICANTE_O_PROVEEDOR, ID_MAR, ID_MOD) VALUES (N'MONITOR LED 74088037', 4, 1, 6, 4, 2, 112, GETDATE(), 1, 2, N'CN0F4WW67426148C0KNL', N'DELL', 3, 5);
INSERT INTO ELEMENTOS_CONFIGURACION (NOMBRE_ELEMENTO_CONFIGURACION, ID_TIPO, ID_ESTADO, PROPIETARIO, ID_DESCRIPCION, ID_IMP_ELE_CONF_HAR, LOCALIZACION_FISICA, FECHA_REGISTRO, RESPONSABLE_REGISTRO, ID_NIVEL, NRO_SERIE, FABRICANTE_O_PROVEEDOR, ID_MAR, ID_MOD) VALUES (N'EQUIPO MULTIFUNCIONAL COPIADORA IMPRESORA SCANNER Y/O FAX 74222358', 5, 1, 154, 5, 2, 7, GETDATE(), 1, 2, N'74634C6600TWP', N'LEXMARK', 5, 6);
-- (elementos restantes desde generate_inserts.py)
GO

PRINT 'SEP2: Datos insertados correctamente'
GO